UltiMafia/Ultimafia

- react_main/src/pages/Play/CreateSetup/CreateSetup.jsx
- react_main/src/pages/Play/Host/Host.jsx
> fix(ui): add correction code for wrong role group count

- .github/workflows/prettier.yml
- Please my brothers and sisters in Christ pray with me.
> Fix prettier workflow

- Games/types/Mafia/roles/Independent/Grouch.js
- Games/types/Mafia/roles/cards/WinIfAliveWhenVillageLose.js
- data/roles.js
> Add Grouch

- Games/types/Mafia/roles/cards/NightRoleBlocker.js
- Games/types/Mafia/templates/death.js
- data/roles.js
I added drunk-drive interactions for Driver and Cyclist.
> Added drunk-drive interactions

- Games/core/Agora.js
- Games/core/Meeting.js
- react_main/package-lock.json
- react_main/package.json
- react_main/public/index.html
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/Game/GhostGame.jsx
- react_main/src/pages/Game/MafiaGame.jsx
- react_main/src/pages/Game/OneNightGame.jsx
- react_main/src/pages/Game/ResistanceGame.jsx
- react_main/src/pages/Game/SplitDecisionGame.jsx
At least I think I am.
Added references to EpicMafia in title & meta tags. I did this because BM is the first result when you search EpicMafia. Secondly, EpicMafia is a relatively easy keyword to target, and I think we can be above them in the search list for it. It would be beneficial for us to do this, because some lost users will still search EpicMafia first, in case it's been a long time.
Also used a free service to get some words to include in the meta descriptions. I.E. using the word "thrilling" 💯 
Also removed Agora js, since it's unused JS and will reduce load times.
I'd appreciate if someone could test this PR out, as I don't have a 100% working dev environment on my laptop. I just want to make sure that the agora stuff I took out still works. Preferably test it AFTER REMOVING …
> Improving SEO

- Games/types/Mafia/roles/cards/Disloyal.js
- Games/types/Mafia/roles/cards/Loyal.js
- data/constants.js
- react_main/src/pages/Learn/LearnMafia.jsx
Added Loyal and Disloyal modifiers, based off @pikulet's code for Vain/Weak.
> Add Loyal and Disloyal

- docs/guide-role-icons.md
- docs/setup-beginner-guide.md
- docs/setup-bot-games.md
- docs/setup-dependencies.md
> docs: fix broken images

- routes/auth.js
> feat: approve users for ranked by default

- Games/core/Game.js
- Games/core/VegKickMeeting.js
> fix: kicks do not include left players, 5 minutes limit to veg kicks and 1 hour limit to pregame

- Games/types/Acrotopia/Game.js
> fix: acrotopia postgame

- Games/types/Acrotopia/Game.js
- Games/types/Acrotopia/Meeting.js
- Games/types/Acrotopia/roles/cards/AcronymGiver.js
- react_main/src/pages/Play/Host/HostAcrotopia.jsx
- routes/game.js
Fixes #536 
Fixes #521 
Fixes #519
> feat(acro): configurable punctuation, standardise caps, JQXZ less frequent

- react_main/package.json
Reverts UltiMafia/Ultimafia#547
Breaks the build.sh script on the server, so reverting it.
> Revert "Allow use of latest node version"

- react_main/package-lock.json
- react_main/package.json
I installed Iconify via Codespaces (as I don't have Node on my computer).
> Installed Iconify

- Games/types/Ghost/data/words.js
> fix(ghost): remove extra word "anger"

- react_main/src/pages/Auth/LogIn.jsx
@DrSharky it's only frontend though
> fix: give generic login message

- Games/core/Player.js
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/Game/MafiaGame.jsx
> fix: last will cannot save in the day

- Games/types/Mafia/roles/Independent/Admirer.js
- Games/types/Mafia/roles/cards/BecomeSKOnDeath.js
- data/roles.js
Admirer from /v/illage courtesy of Vastined. Only attached to SKs
> feat: admirer role

- react_main/src/components/Popover.jsx
- react_main/src/components/Roles.jsx
it still has another bug but this will make it less annoying first
> fix popover not closing

- Games/core/Game.js
> don't make games unranked if dead player leaves

- react_main/src/pages/Game/AcrotopiaGame.jsx
- react_main/src/pages/Game/GhostGame.jsx
- react_main/src/pages/Game/JottoGame.jsx
- react_main/src/pages/Game/OneNightGame.jsx
- react_main/src/pages/Game/ResistanceGame.jsx
- react_main/src/pages/Game/SecretHitlerGame.jsx
- react_main/src/pages/Game/SplitDecisionGame.jsx
> fix: textmeetinglayout new param bug from #631

- Games/types/Acrotopia/Game.js
- Games/types/Jotto/Game.js
- Games/types/Jotto/Player.js
- Games/types/Jotto/roles/cards/GuessWord.js
- Games/types/Jotto/roles/cards/SelectWord.js
- Games/types/Jotto/roles/cards/WinIfCorrectGuess.js
- Games/types/Jotto/utils.js
- react_main/src/components/Popover.jsx
- react_main/src/css/gameJotto.css
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/Game/JottoGame.jsx
- react_main/src/pages/Play/Host/HostJotto.jsx
- react_main/src/utils.jsx
- routes/game.js
- routes/setup.js
Fixes #668 
partially fixes #660
> fix: acrotopia and jotto fixes, combined meetings now allow quoting

- Games/types/Mafia/items/Gamble.js
- Games/types/Mafia/roles/cards/WinWithTwoGambleWins.js
Gambler's wincon was broken! pulled directly from /v/ to fix it
> fix: gambler win

- react_main/src/components/Basic.jsx
- react_main/src/pages/Game/Game.jsx
> fix: replace quoted swears w/ the same values

- Games/core/Card.js
- Games/core/Role.js
- Games/types/Mafia/roles/Independent/Politician.js
- Games/types/Mafia/roles/cards/ChangeRandomAlignment.js
- Games/types/Mafia/roles/cards/WinWithCurrentAlignment.js
- data/roles.js
Politician from EM, courtesy of /v/. Vastined's code, I only changed a few strings to add support for the Cult.
> feat: Politician from EM

- Games/types/Mafia/effects/Famished.js
- Games/types/Mafia/roles/Independent/Sidekick.js
- Games/types/Mafia/roles/cards/Lone.js
- Games/types/Mafia/roles/cards/WinWithIndependentLead.js
- data/roles.js
Sidekick from EM. Code provided by Vastined
Lone should now offer all Lone Mafia to trade their power role for joining the nightkill. Code by me, help from Egg and Sand
> feat: Sidekick role, Lone offers all non-meeting Mafia to convert to meeting Mafioso

- Games/types/Mafia/roles/Independent/Occultist.js
> fix: typo in occultist card

- Games/types/Mafia/effects/Poison.js
> fix(mafia): poison kills have power 2

- Games/types/Mafia/Player.js
> fix(mafia): enable pregame quoting

- react_main/src/css/roles.css
> fix(ui): closed role count remove scrollbar

- Games/types/Mafia/roles/cards/NeighborAlignment.js
> fix(mafia): empath does not work when dead (counter is off)

- Games/core/Winners.js
> fix: win announcement does not show brackets if no winners

- Games/types/Mafia/roles/cards/AlignmentLearnerDelayed.js
> fix(mafia): lazy cop should get same report as cop from previous night

- Games/types/Mafia/items/Armor.js
- Games/types/Mafia/roles/Mafia/Gramps.js
- Games/types/Mafia/roles/Village/Granny.js
- Games/types/Mafia/roles/cards/KillImmune.js
- Games/types/Mafia/roles/cards/KillVisitors.js
> fix(mafia): kill immune should have default lifespan of Infinity

- react_main/src/components/Popover.jsx
- react_main/src/components/Roles.jsx
> feat: add modifier to popover

- react_main/src/components/Basic.jsx
- react_main/src/pages/Community/Comments.jsx
> video-embeds

- Games/types/Mafia/roles/Village/Chauffeur.js
- Games/types/Mafia/roles/cards/NightRoleBlocker.js
- Games/types/Mafia/templates/death.js
> fix: cyclist chauffeur wincount mixed up

- react_main/src/components/Emotes.jsx
> fixed golb emote

- react_main/src/pages/Game/Game.jsx
> feat(ui): quotes show from state instead of meeting name

- Games/core/Player.js
- Games/types/Mafia/Action.js
- Games/types/Mafia/effects/Silenced.js
- Games/types/Mafia/roles/cards/Silencer.js
> fix(mafia): silenced target will not know they are silenced

- Games/types/Mafia/roles/cards/RevealNameToTarget.js
- Games/types/Mafia/roles/cards/RevealRoleToTarget.js
- data/modifiers.js
> feat: add noisy and clumsy modifiers by r9

- Games/types/Mafia/roles/cards/GuardianAngel.js
> fix(mafia): angel should not use power when selecting no

- data/modifiers.js
> fix(mafia): rename suspect to shady

- Games/types/Mafia/roles/Independent/Ripper.js
- data/roles.js
- react_main/src/components/Popover.jsx
- react_main/src/components/Roles.jsx
- react_main/src/components/Setup.jsx
- react_main/src/css/roles.css
- routes/game.js
- routes/roles.js
- routes/setup.js
Ported from /v/illage, code by vastined
> feat: rolegroups popover changes

- routes/setup.js
> fix(role groups): sort all rolesets, not just the first

- Games/core/Game.js
probably just a commit oversight, no worries.
> Set pregame countdown timer back to 1 hr

- react_main/src/components/Basic.jsx
- react_main/src/components/Roles.jsx
- react_main/src/components/Setup.jsx
- react_main/src/css/join.css
- react_main/src/css/main.css
- react_main/src/css/play.css
- react_main/src/css/setup.css
- react_main/src/pages/Play/Join.jsx
> style: improve UI (gamelist, hovering roles/setups/playerCount, lobby fill bar)

- react_main/src/components/Roles.jsx
[Screencast from 01-08-2023 00:44:02.webm](https://github.com/UltiMafia/Ultimafia/assets/24848927/f1d79c33-53af-4ae4-911c-ced0d2303a00)
> fix(ui): temp fix for hovering over roles in create setup deleting roles

- data/constants.js
- react_main/src/components/Roles.jsx
- react_main/src/css/host.css
- react_main/src/css/join.css
- react_main/src/css/play.css
- react_main/src/css/roles.css
- react_main/src/css/setup.css
- react_main/src/pages/Play/Join.jsx
```
[✅] make Roles hoverable (ensure createSetup works = hovering doesn't remove roles)
[✅] display more games in GAMELIST (8 -> 12? 10?)
[✅] lock button is shit
[✅] ? open role is shit
[✅] JOIN button is unclickable (only the 'text' is)
[✅] show crashed+private game icons inline
[✅] remove border-radius for roles (no longer conceal them!)
```
> fix: fix "UI overhaul 1" broken styles & more

- react_main/src/css/play.css
> fix: fix /play/host itemlist height

- react_main/src/pages/Game/Game.jsx
> feat(ui): add lock/unlock icon to last will

- Games/types/Mafia/roles/Village/President.js
- Games/types/Mafia/roles/cards/Polariser.js
- Games/types/Mafia/roles/cards/WinFourPolarisedDeaths.js
- Games/types/Mafia/roles/cards/WinIfDiesWithDoll.js
- Games/types/Mafia/roles/cards/WinWithMafia.js
- Games/types/Mafia/templates/death.js
- data/roles.js
cg can't win if dead, polar bears win on achieving majority
president no longer kills all villagers on death. works like on EM (1 prez death = mafia win). didn't edit the linchpin card though
> feat: improved Creepy Girl and Polar Bear logic, President rework

- Games/types/Mafia/roles/Independent/VengefulSpirit.js
> fix(mafia): vengeful spirit cannot kill when condemned

- Games/types/Mafia/roles/cards/Lone.js
- data/roles.js
right now, lone only has 1 option if you are mafia: "yes" to become mafioso
quick fix to change this
> fix: lone should have yes and no options

- react_main/src/css/roles.css
> fix broken css from #925

- react_main/src/css/markdown.css
Changed the color from white/black depending on theme to blue, as it should be.
> Fix hyperlink colors on forums/profiles

- Games/types/Mafia/roles/Independent/Siren.js
weird vastined thing, now corrected
> fix: siren is not hostile

- Games/types/Mafia/roles/cards/WinAllProbed.js
- Games/types/Mafia/roles/cards/WinByStealingClovers.js
- Games/types/Mafia/roles/cards/WinFourPolarisedDeaths.js
- Games/types/Mafia/roles/cards/WinInsteadOfVillage.js
Added flavor text to Autocrat, Polar Bear, Alien, Leprechaun
in the future, probably every independent will have flavor text as well as a lot of the major roles. Just need to write it all
> feat: more flavor text

- data/modifiers.js
> fix(mafia): update oblivious description that it does not meet

- react_main/src/components/Basic.jsx
> fix(ui): add pop up warning when clicking on links

- react_main/src/pages/Game/Game.jsx
> fix(ui): fix typing bubbles alignment

- Games/types/Mafia/Winners.js
- Games/types/Mafia/items/Invitation.js
- Games/types/Mafia/items/Summon.js
- Games/types/Mafia/roles/Hostile/Nyarlathotep.js
- Games/types/Mafia/roles/cards/AnonymizeCult.js
- Games/types/Mafia/roles/cards/AnonymizeMafia.js
- Games/types/Mafia/roles/cards/MeetWithTemplars.js
- Games/types/Mafia/roles/cards/MeetingCult.js
- Games/types/Mafia/roles/cards/SeanceTarget.js
- Games/types/Mafia/roles/cards/WinInsteadOfCult.js
- data/roles.js
Nyarlathotep from role patrol thread
Cult-targeting Mastermind that makes visitors go crazy like Cthulhu
> feat: nyarlathotep role

- Games/types/Mafia/roles/cards/AlignmentLearnerParanoid.js
- Games/types/Mafia/roles/cards/CanProbe.js
- Games/types/Mafia/roles/cards/WinAllProbed.js
> fix: aliens meet with each other

- data/renamedRoles.js
- data/roles.js
butler is the worst role in all of existence
if RickSanchez wants it back he can DM me. it is a waste of space. it is a worse Godfather
"the butler always does it" yeah not anymore
> fix: butler role is kill

- Games/types/Mafia/Meeting.js
- Games/types/Mafia/roles/Cult/Baphomet.js
- data/roles.js
Baphomet role based on my personal role archive
meets with both templars and cult
> feat: baphomet role

- Games/types/Mafia/roles/cards/Telepathic.js
- data/modifiers.js
based on telepath/whisperer roles from EM; contact any player in secret
> feat: telepathic modifier

- Games/types/Mafia/roles/cards/MonkSave.js
- Games/types/Mafia/roles/cards/WinIfPrescientVote.js
similar to siren's flavor text for a successful beckon
> feat: flavor text for monk/warlock

- Games/types/Mafia/roles/cards/Carol.js
- Games/types/Mafia/roles/cards/Dream.js
- data/roles.js
nobody ever thought to make dreamer/caroler compatible with cult
this is why making 1:1 copy of EM mechanics is painful ):
> fix: dreamer and caroler detect cult/hostiles

- Games/types/Mafia/roles/cards/GuardianAngel.js
- data/roles.js
Angel can now save their target even if dead, as long as they haven't already used their action
> feat: angel can act while alive or dead

- Games/types/Mafia/roles/cards/AlignmentLearner.js
- Games/types/Mafia/roles/cards/AlignmentLearnerDelayed.js
- Games/types/Mafia/roles/cards/AlignmentLearnerNaive.js
- Games/types/Mafia/roles/cards/AlignmentLearnerParanoid.js
- Games/types/Mafia/roles/cards/AlignmentLearnerRandom.js
- Games/types/Mafia/roles/cards/AlignmentLearnerReversed.js
people said the messages are too similar, so now they're clarified as innocent or guilty
> fix: cop clarity in system messages

- Games/types/Mafia/effects/KillImmune.js
- Games/types/Mafia/roles/cards/KillImmune.js
> fix(mafia): default duration of killimmune should be infinity

- Games/types/Mafia/Action.js
> fix(mafia): getVisitors can correct get multiactor visits

- Games/types/Secret Hitler/Game.js
- Games/types/Secret Hitler/items/Execute.js
- Games/types/Secret Hitler/roles/cards/WinWithLiberals.js
> fix(sh): game ends instantly if hitler left

- Games/types/Mafia/roles/cards/OneShot.js
> fix(mafia): one shot roles can attend the party multiple times

- Games/types/Mafia/roles/Mafia/Ninja.js
- Games/types/Mafia/roles/cards/MakeKillHidden.js
- Games/types/Mafia/roles/cards/MeetingMafia.js
affects all kills
ninja is now rolebloackable
Fixes #1036
> fix(mafia): mafia is multiactor, fix ninja it affects all kills

- data/contributors.js
- react_main/src/pages/Community/Contributors.jsx
> 8 22 art contributors

- data/modifiers.js
> Add Gossipy Modifier

- Games/types/Secret Hitler/Game.js
- Games/types/Secret Hitler/items/Execute.js
- Games/types/Secret Hitler/roles/cards/WinWithLiberals.js
> fix(secret hitler): if anyone leaves, game ends no one wins

- Games/types/Mafia/Action.js
- Games/types/Mafia/roles/Mafia/Lobotomist.js
- Games/types/Mafia/roles/cards/Vanillaise.js
- data/roles.js
- react_main/src/constants/slangList.js
Name was conceived by @Golbolco
Abilities:
Slang:
> Add Lobotomist

- Games/types/Mafia/roles/cards/Carol.js
D1 https://ultimafia.com/game/XAWqti_or/review
this probably should not happen! no more repeats in carol
> fix: no repeats in carol

- Games/types/Mafia/roles/Cult/Doomsayer.js
- Games/types/Mafia/roles/cards/ConvertVisitors.js
- data/roles.js
adapted from mafiauniverse's Black Goo
alt for cult leader. converts visitors to cultist
> feat: doomsayer role

- Games/types/Mafia/roles/cards/WinWithCult.js
- Games/types/Mafia/roles/cards/WinWithMafia.js
> fix(mafia): mafia and traitors can win without voting off every traitor

- react_main/src/components/Emotes.jsx
> fix(emotes): ignore object prototype like constructor

- react_main/src/Main.jsx
> fix(ui): configure descriptive text for link

- react_main/src/pages/Play/CreateSetup/CreateSetup.jsx
> feat(ui): enable hover when creating setup

- react_main/src/pages/Game/Game.jsx
> feat(game, ui): save speech across state

- Games/types/Mafia/roles/cards/CleanDeath.js
> fix(mafia): janitor should not go through armour

- Games/types/Mafia/roles/cards/KeyGiver.js
adds the ability for keymaker to visit self
> Keymaker Self Visit

- react_main/src/css/game.css
- react_main/src/css/join.css
fixed lobby rows stretching, and miscellaneous game option icons from increasing in size.
> fix lobby styling & game icon styling

- Games/types/Mafia/roles/cards/NightKiller.js
Fixes (partially) #1150 , though vigi can still attack if killed by CM and the like
> feat(mafia): vigilante cannot kill the night it dies to mafia

- Games/types/Mafia/items/Timebomb.js
> fix(mafia): maided anarchist will die to bomb

- Games/core/Winners.js
- Games/types/Mafia/roles/cards/WinIfDead.js
> fix(mafia): allow phantom to win when no one is alive

- Games/types/Mafia/roles/cards/BondedForLife.js
> fix(mafia): allow lover to win

- data/roles.js
> fix(mafia): clarify tea lady role description

- react_main/src/css/game.css
> fix(ui): further reduce the size of game title for medium screens

- Games/types/Mafia/roles/cards/OneShot.js
> fix(mafia): oneshot mafia can attend mafia meeting daily

- react_main/src/pages/Game/Game.jsx
> fix(ui): fix review of old games before anon deck update

- Games/types/OneNight/Game.js
Change specification of when the game ends.
> Fix one night having 2 nights

- Games/core/Player.js
Fixed not being able to leave anonymous games.
> Fixed not leaving anon-games

- app.js
- package-lock.json
- package.json
Add the text compression NPM module and set the text compression filter on ExpressJS.
> Enable text compression in express

- Games/types/Jotto/Game.js
> fix competitive jotto scoring

- Games/types/Mafia/roles/cards/WinWithCult.js
- Games/types/Mafia/roles/cards/WinWithMafia.js
> fix(mafia): benandante contributes to majority count

- react_main/src/pages/Community/Community.jsx
https://discord.com/channels/1102713221711925339/1107424127721144330/threads/1154855859902492684
> Remove Emotes Page

- Games/types/Mafia/roles/Village/Whistleblower.js
- data/roles.js
whistleblower is not balanced as a mafia role, moved to village instead
> feat: whistleblower joins the village

- Games/core/Game.js
- Games/core/Meeting.js
- Games/types/Mafia/roles/cards/VillageCore.js
- db/schemas.js
- modules/redis.js
- react_main/src/components/Popover.jsx
- react_main/src/pages/Play/Host/HostMafia.jsx
- react_main/src/pages/Play/Join.jsx
- routes/game.js
Added noveg as an option for hosting a game of mafia.
Removed noveg as a flag from VillageCore.js
> Noveg removed from village core, made game host option

- Games/core/Game.js
> potential fix

- Games/types/Mafia/roles/cards/GiveCrystal.js
- Games/types/Mafia/roles/cards/GivePresents.js
- data/roles.js
gonna merge this preemptively just because I want santa to give out all the items
> 12 15 role audit

- Games/types/Mafia/roles/cards/DivinerPrediction.js
- data/roles.js
I cleaned up its description and did some refactoring.
> hotfix: diviner refactor

- react_main/src/Main.jsx
- react_main/src/css/main.css
(conditional rendering breaks the site, otherwise)
> fix: use "import" instead of "require" + fix "asd" font name

- react_main/src/Main.jsx
- react_main/src/css/chat.css
- react_main/src/css/main.css
- react_main/src/css/nav.css
- react_main/src/pages/Chat/Chat.jsx
> feat: allow closing/reopening the chat Tab & fix UI jitter (scrollbar houdini shit)

- react_main/src/components/Roles.jsx
- react_main/src/components/Setup.jsx
- react_main/src/components/usePopoverOpen.jsx
- react_main/src/css/main.css
- react_main/src/pages/Game/Game.css
- react_main/src/pages/Game/Game.jsx
> feat: add new Popover for Role icons & fix useless scrollbar appearing in-game

- react_main/src/components/Roles.jsx
- react_main/src/pages/Play/CreateSetup/CreateMafiaSetup.jsx
also revert that one digits thing I did,
because it shouldn't need to be there?
> fix create closed role group setup

- react_main/src/components/Setup.jsx
> Fixed Final Modifier Being Cut Off

- Games/types/Mafia/roles/cards/NightCaroler.js
fixed conditional for what the carol is based on
> caroler fix

- react_main/src/pages/Play/LobbyBrowser/LobbyBrowser.jsx
- routes/game.js
closes #1486
Didn't remove 'All' lobby logic from all the files, so it's backward compatible if users manually go to /play?lobby=All
> feat(site): Remove "All" lobby tab, add an open game count badge to tabs

- react_main/src/css/main.css
- react_main/src/pages/Welcome/Welcome.jsx
Logo and icons for Pride Month
> feat: CSS for Pride month

- Games/games.js
- Games/types/LiarsDice/Game.js
- Games/types/LiarsDice/items/Microphone.js
- react_main/src/pages/Game/LiarsDiceGame.jsx
- routes/setup.js
can't input 0 anymore
increasing dice doesnt let you lower bid
leaving games doesnt show "player left but dice will keep count this round" message
1's are counted correctly in wild ones
doesn't skip turns anymore
added (LIE CALL) infront of lie calls to see them better and put nextPlayerName is guessing... text under the lie call
added 2 sounds for dice rolls
> a bunch of LD stuff

- Games/types/LiarsDice/Game.js
- Games/types/LiarsDice/items/Microphone.js
- react_main/src/css/game.css
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/Game/LiarsDiceGame.jsx
CHANGES
- Fixed Spot On
- Removed Double System Message on wrongly calling a lie
- Settings shown in pre game
- On leave system message fixes
- Fixed turns getting skipped... hopefully
- Fixed bidding amount message not showing on high numbers
> Settings shown in pre game and a bunch of fixes

- README.md
- data/roles.js
- react_main/src/components/Nav.jsx
- react_main/src/constants/themes.jsx
- react_main/src/pages/Learn/Learn.jsx
- react_main/src/pages/Learn/LearnMafia.jsx
- react_main/src/pages/Policy/Policy.jsx
- react_main/src/pages/Policy/Rules.jsx
Partially implements https://github.com/UltiMafia/Ultimafia/issues/1491
> chore(UI): Slang table moved to Learn.jsx

- react_main/src/constants/themes.jsx
- react_main/src/pages/Learn/Learn.jsx
- react_main/src/pages/Learn/LearnAcrotopia.jsx
- react_main/src/pages/Learn/LearnGhost.jsx
- react_main/src/pages/Learn/LearnJotto.jsx
- react_main/src/pages/Learn/LearnLiarsDice.jsx
- react_main/src/pages/Learn/LearnMafia.jsx
- react_main/src/pages/Learn/LearnOneNight.jsx
- react_main/src/pages/Learn/LearnResistance.jsx
- react_main/src/pages/Learn/LearnSecretDictator.jsx
- react_main/src/pages/Learn/LearnSplitDecision.jsx
- react_main/src/pages/Learn/LearnWackyWords.jsx
- react_main/src/pages/Policy/Rules.jsx
Partially implements https://github.com/UltiMafia/Ultimafia/issues/1491
> chore: most of Learn page rewritten using material UI

- react_main/src/pages/Learn/LearnMafia.jsx
- react_main/src/pages/Policy/Policy.jsx
- react_main/src/pages/Policy/Report.jsx
- routes/report.js
> revert site back to webhook fix

- react_main/src/pages/Policy/Policy.jsx
- routes/report.js
uncommented report page + syntax fix on res.status(500)
> show report page

- react_main/src/constants/themes.jsx
- react_main/src/pages/Learn/Learn.jsx
- react_main/src/pages/Learn/LearnAcrotopia.jsx
- react_main/src/pages/Learn/LearnGhost.jsx
- react_main/src/pages/Learn/LearnJotto.jsx
- react_main/src/pages/Learn/LearnLiarsDice.jsx
- react_main/src/pages/Learn/LearnMafia.jsx
- react_main/src/pages/Learn/LearnOneNight.jsx
- react_main/src/pages/Learn/LearnResistance.jsx
- react_main/src/pages/Learn/LearnSecretDictator.jsx
- react_main/src/pages/Learn/LearnSplitDecision.jsx
- react_main/src/pages/Learn/LearnWackyWords.jsx
New custom expand icons + more consistent Learn page
> fix: expand icons

- react_main/src/pages/Community/Moderation.jsx
- react_main/src/pages/Community/UserSearch.jsx
Reverts UltiMafia/Ultimafia#1579
> Revert "feat(site): mUI for usersearch.jsx" because it looks awful the more users you register

- data/constants.js
- react_main/src/Main.jsx
- react_main/src/css/play.css
- react_main/src/pages/Community/Community.jsx
- react_main/src/pages/Community/UserSearch.jsx
- react_main/src/pages/Fame/Contributors.jsx
- react_main/src/pages/Fame/Fame.jsx
- react_main/src/pages/Learn/Learn.jsx
- react_main/src/pages/Policy/Policy.jsx
- react_main/src/pages/Policy/PrivacyPolicy.jsx
- react_main/src/pages/Policy/Report.jsx
- react_main/src/pages/Policy/Rules.jsx
- react_main/src/pages/Policy/TermsOfService.jsx
- routes/mod.js
partially implements https://github.com/UltiMafia/Ultimafia/issues/1491
> feat(site): redux usersearch and learn pages

- react_main/public/index.html
- react_main/src/Main.jsx
- react_main/src/components/Roles.jsx
- react_main/src/css/main.css
- react_main/src/css/nav.css
- react_main/src/pages/Chat/Chat.jsx
- react_main/src/pages/User/UserNotifications.jsx
- react_main/src/pages/Welcome/Welcome.jsx
While fixing the frontend code, it was observed that `height` was set explicitly across several elements where it was not necessary.
Given that the codebase needs to be optimised, I went ahead and removed all instances of explicitly set `height` properties that did not appear to be necessary. This was problematic.
There is likely inner logic in the games components where the main chat area inherits the height through a chain that leads to the `#root` element.
> debug (games): height must be explicitly set for #root

- Games/types/Mafia/effects/CursedCult.js
- Games/types/Mafia/roles/Cult/Mezepheles.js
- Games/types/Mafia/roles/cards/CurseWithWordCult.js
- data/roles.js
Added a Cult Aligned version of Jinx. It converts players to Cultist instead of killing.
I didn't test it so It probably doesn't work.
> Cult Jinx Role (Mezepheles)

- data/donors.js
- react_main/public/sitemap.xml
- react_main/src/pages/Fame/Donors.jsx
- react_main/src/pages/Fame/Fame.jsx
- react_main/src/pages/Learn/Learn.jsx
- routes/site.js
partial implementation of https://github.com/UltiMafia/Ultimafia/issues/1562
> feat(site): Donor page

- Games/types/Mafia/roles/Village/Analyst.js
- Games/types/Mafia/roles/cards/GuessFiveRoles.js
- data/roles.js
It guesses 5 player's roles and learns how many of it's guesses were Correct.
I named it Analyst but a better name probably exists.
> Analyst Role (Juggler from Blood on the Clock Tower)

- Games/types/Mafia/roles/Village/Laundress.js
- Games/types/Mafia/roles/cards/LearnOneOfTwoPlayers.js
- Games/types/Mafia/roles/cards/Omniscient.js
- data/modifiers.js
- data/roles.js
Laundress learn 1 of 2 players is a Town,Mafia, or Cult role on Night 1.
Omniscient Modifier, Roles with this Modifier learn all visits every night and learn all players' roles.
> Added Laundress (Washerwomen + Investigator from BOTC) and Omniscient Modifier (Spy/Widow from BOTC).

- Games/types/Mafia/roles/Village/Appraiser.js
- Games/types/Mafia/roles/cards/EvilPairs.js
- Games/types/Mafia/roles/cards/KillorPass.js
- data/roles.js
Appraiser learns how many instances of 2 Evil Players neighboring are occurring on night 1. 
The Imp bug was caused by the rename.
> Added Appraiser (Chef from BOTC) and Fixed an Imp bug

- Games/types/Mafia/roles/cards/GuessFiveRoles.js
- data/roles.js
Analyst now has UI just like Justice.
Analyst now can't choose a role or player twice.
> Improved Analyst UI

- .github/workflows/prettier.yml
- .github/workflows/unit-test.yml
- .prettierignore
Ensure consistent code format
automatically fixes code styles by itself.
run unit tests in a separate workflow
> Run prettier automatically

- Games/types/Mafia/Player.js
- Games/types/Mafia/items/Stake.js
- Games/types/Mafia/roles/Village/Saint.js
- Games/types/Mafia/roles/cards/GuessFiveRoles.js
- Games/types/Mafia/roles/cards/KillAlignedOnCondemn.js
- data/roles.js
Saint kills all town aligned players if condemned. If killed by another method nothing happens. Unlike President/Linchpin no one knows you are the Saint.
> Saint role from Blood on the Clocktower

- react_main/src/css/play.css
- react_main/src/pages/Play/LobbyBrowser/LobbyBrowser.jsx
- react_main/src/pages/Play/Play.jsx
closes https://github.com/UltiMafia/Ultimafia/issues/1627
> feat(site): consistent appbar on Play page

- Games/types/Mafia/roles/cards/NightComedian.js
> do not allow target to be in the joke

- Games/types/Mafia/roles/Village/Nun.js
- Games/types/Mafia/roles/cards/RemoveModifers.js
- data/roles.js
Nun can remove other players' role modifiers.
> Added Nun Role

- Games/types/Mafia/roles/cards/BanishedRole.js
Added the BanishedRole.js file I forgot.
> Banished fix 

- Games/core/Game.js
- Games/types/Mafia/items/ShavingCream.js
- Games/types/Mafia/roles/Cult/EvilTwin.js
- Games/types/Mafia/roles/Cult/Succubus.js
- Games/types/Mafia/roles/Village/Barber.js
- Games/types/Mafia/roles/Village/Investigator.js
- Games/types/Mafia/roles/Village/Maiden.js
- Games/types/Mafia/roles/cards/EvilDistance.js
- Games/types/Mafia/roles/cards/GiveShavingCreamOnDeath.js
- Games/types/Mafia/roles/cards/LearnGoodAndEvilRole.js
- Games/types/Mafia/roles/cards/NightMindRot.js
- Games/types/Mafia/roles/cards/SwapRolesIfEvil.js
- Games/types/Mafia/roles/cards/Twins.js
- Games/types/Mafia/roles/cards/WinWithCult.js
- data/donors.js
- data/roles.js
Barber, If a Barber dies A random Cult or Mafia player gets to switch two players roles.
Snake Charmer added as Maiden, Each night a Maiden selects a player if that player is mafia or cult, They switch roles with the Maiden.
Dreamer added as Investigator, Each choose a player to learn 2 roles. One is the player's real role and one is a role of the opposite alignment.
Evil Twin, At the start of the game an Evil Twin is assigned a Good Twin. The Two Twins learn each others roles. If the Good Twin is condemned Cult Wins.
Added a Message that appears if the base Banished Count is greater then 0. It tells players the base Banished count.
> Added Snake Charmer, Barber, Evil Twin, Dreamer from BOTC. Minor improvement to Banished roles.

- Games/core/Game.js
- Games/types/Mafia/roles/Village/Philosopher.js
- Games/types/Mafia/roles/Village/Princess.js
- Games/types/Mafia/roles/cards/Add1Banished.js
- Games/types/Mafia/roles/cards/Add2Banished.js
- Games/types/Mafia/roles/cards/ConvertSelfToChosenRole.js
- Games/types/Mafia/roles/cards/ConvertToChosenRole.js
- Games/types/Mafia/roles/cards/IfVotedForceCondemn.js
- Games/types/Mafia/roles/cards/Learn2ExcessOr1Role.js
- Games/types/Mafia/roles/cards/Learn3ExcessRoles.js
- Games/types/Mafia/roles/cards/LearnOneOfTwoPlayers.js
- Games/types/Mafia/roles/cards/Remove1Banished.js
- data/contributors.js
- data/modifiers.js
- data/roles.js
Princess now Overturns the vote at the end of the day.
Philosopher can choose to convert to any village role that can spawn in the setup. If the role they convert to is already in play, The player with that role is blocked (Succubus style) for the rest of the game.
> Princess Changes and Philosopher role from BOTC

- Games/types/Mafia/Action.js
- Games/types/Mafia/items/PermaMindRot.js
- Games/types/Mafia/roles/cards/KillAndCreateUndead.js
- db/schemas.js
- react_main/src/Main.jsx
- react_main/src/constants/themes.jsx
- react_main/src/pages/User/Settings.jsx
Closes https://github.com/UltiMafia/Ultimafia/issues/1494
> feat(site): Light Mode reenabled

- Games/core/Game.js
- Games/types/Mafia/roles/Cult/Tormentor.js
- Games/types/Mafia/roles/Mafia/Hider.js
- Games/types/Mafia/roles/Village/Seeker.js
- Games/types/Mafia/roles/cards/Add1Banished.js
- Games/types/Mafia/roles/cards/Add2Banished.js
- Games/types/Mafia/roles/cards/AddHideAndSeek.js
- Games/types/Mafia/roles/cards/AddOrRemove1Banished.js
- Games/types/Mafia/roles/cards/GuessAdversaryConvert.js
- Games/types/Mafia/roles/cards/GuessAdversaryKill.js
- Games/types/Mafia/roles/cards/KillIfBanishedDiedDuringDay.js
- Games/types/Mafia/roles/cards/Remove1Banished.js
- react_main/src/Main.jsx
- react_main/src/pages/User/UserNotifications.jsx
Reverts UltiMafia/Ultimafia#1700
> Revert "fix: openAnnouncements"

- Games/core/Game.js
- Games/core/History.js
- Games/core/Meeting.js
- Games/core/Player.js
- Games/types/Mafia/Action.js
- Games/types/Mafia/items/Drama.js
- Games/types/Mafia/items/IsTheLunatic.js
- Games/types/Mafia/roles/Mafia/Ghostbuster.js
- Games/types/Mafia/roles/Village/Exorcist.js
- Games/types/Mafia/roles/cards/ActAliveOrDead.js
- Games/types/Mafia/roles/cards/BecomeAlignmentOfVisitors.js
- Games/types/Mafia/roles/cards/BecomeFakeCultRole.js
- Games/types/Mafia/roles/cards/Disloyal.js
- Games/types/Mafia/roles/cards/KillVillagePlayerOnDeath.js
- Games/types/Mafia/roles/cards/Loyal.js
- Games/types/Mafia/roles/cards/MeetingCult.js
- Games/types/Mafia/roles/cards/NightCaroler.js
- Games/types/Mafia/roles/cards/NightExorcise.js
- Games/types/Mafia/roles/cards/StartDrama.js
- Games/types/Mafia/roles/cards/UnluckyDeath.js
- Games/types/Mafia/roles/cards/VillageCore.js
- Games/types/Mafia/roles/cards/WinWithCult.js
- Games/types/Mafia/roles/cards/WinWithCurrentAlignment.js
- Games/types/Mafia/roles/cards/WinWithVillage.js
- data/modifiers.js
- data/roles.js
- react_main/src/pages/Game/Game.jsx
Added Exorcist, Each night choose a dead player, That player is exorcised, They can't use any graveyard abilities, Be revived, or be targeted.
added Ghostbuster,  Is the same as Exorcist but is mafia.
Players who veg are exorcised.
The Underworld only shows in side menu if a player vegs and will not shows during the reviews. It will also sometimes show to the Exorcised Player. (I do not know how to fix it) 
The roles and vegging did function correctly in testing.
> Add Exorcist and Ghosthunter + Underworld (Display does not work)

- Games/core/Game.js
- Games/core/Meeting.js
- Games/types/Mafia/Action.js
- Games/types/Mafia/roles/cards/ActAliveOrDead.js
- Games/types/Mafia/roles/cards/Endangered.js
- Games/types/Mafia/roles/cards/KillCultistsOnDeath.js
- Games/types/Mafia/roles/cards/MeetingCult.js
- Games/types/Mafia/roles/cards/VillageCore.js
- Games/types/Mafia/roles/cards/WinWithCult.js
- Games/types/Mafia/roles/cards/WinWithVillage.js
- react_main/src/constants/slangList.js
- react_main/src/pages/Game/Game.jsx
Rename was not Completed Properly. This should fix it unless I missed a spot.
> Televangelist fix

- Games/types/Mafia/items/PermaMindRot.js
- Games/types/Mafia/roles/Cult/Devotee.js
- Games/types/Mafia/roles/Cult/Zealot.js
- Games/types/Mafia/roles/Independent/PandaBear.js
- Games/types/Mafia/roles/Independent/Rival.js
- Games/types/Mafia/roles/Independent/VicePresident.js
- Games/types/Mafia/roles/Village/Senator.js
- Games/types/Mafia/roles/cards/AddCopyOfRole.js
- Games/types/Mafia/roles/cards/AddMultipleCopy.js
- Games/types/Mafia/roles/cards/AddRottenCopy.js
- Games/types/Mafia/roles/cards/ConquerAlignment.js
- Games/types/Mafia/roles/cards/Devotion.js
- Games/types/Mafia/roles/cards/Endangered.js
- Games/types/Mafia/roles/cards/EndangeredGraveyard.js
- Games/types/Mafia/roles/cards/KillAlignedOnCondemn.js
- Games/types/Mafia/roles/cards/KillAlignedOnDeath.js
- Games/types/Mafia/roles/cards/KillCultistsOnDeath.js
- Games/types/Mafia/roles/cards/VampireSetup.js
- Games/types/Mafia/roles/cards/WinSwap.js
- Games/types/Mafia/roles/cards/WinWithFaction.js
- Games/types/Mafia/roles/cards/ZealotCondemn.js
- data/contributors.js
- data/modifiers.js
- data/roles.js
- react_main/public/index.html
- react_main/src/constants/themes.jsx
- react_main/src/css/game.css
special thanks to View for the spiderweb gif
> chore: Halloween Theme

- Games/types/Mafia/Game.js
- Games/types/Mafia/items/Microphone.js
- Games/types/Mafia/roles/Independent/Ghost.js
- Games/types/Mafia/roles/cards/GuessWordOnCondemn.js
- Games/types/Mafia/roles/cards/MeetingGhost.js
- Games/types/Mafia/roles/cards/WinWithGhost.js
- data/contributors.js
- data/renamedRoles.js
- data/roles.js
- react_main/src/css/roles.css
Probably some broken stuff in here
> feat: Ghost Merge, no UI yet

- react_main/src/Main.jsx
- react_main/src/css/main.css
- react_main/src/pages/Welcome/Welcome.jsx
Art currently exists for default, halloween, and pride (no holiday-theme for December yet)
> feat: site logo updates automatically on relevant months

- Games/core/Game.js
- Games/core/Player.js
- Games/types/Mafia/Game.js
- Games/types/Mafia/items/Retirement.js
- Games/types/Mafia/roles/cards/BecomeRoleForNight.js
- Games/types/Mafia/roles/cards/LearnIfRoleChanged.js
- Games/types/Mafia/roles/cards/MindRotRoleFor3Nights.js
- Games/types/Mafia/roles/cards/Retired.js
- Games/types/Mafia/roles/cards/SwapRolesOnce.js
- Games/types/Mafia/roles/cards/SwapTwoOtherRoles.js
- Games/types/Mafia/roles/cards/VampireSetup.js
- Games/types/Mafia/roles/cards/WinWithFaction.js
- data/modifiers.js
- data/roles.js
- db/schemas.js
- react_main/src/pages/Play/CreateSetup/CreateMafiaSetup.jsx
- routes/setup.js
Add One Night game option, Game ends after Day 1. Village wins if they kill One mafia/cult. Mafia/Cult wins if all Mafia/Cult are Alive. If no Mafia/Cult Village wins if no Village died. If Mafia and Cult are present, Village must kill 1 of each. Mafia must kill 1 Cult. Cult must kill one 1 mafia. (Some Independents will need to be adjusted but that will done later)
Hidden Converts, Hides all role changes
Enchantress now activates Exorcise Village Meeting.
Sensible learn what your role is at end of night.
Retired, Become a Vanilla role that learns Original roles.
> One Night Stuff

- Games/types/Mafia/roles/cards/ConvertSelfToChosenRole.js
- Games/types/Mafia/roles/cards/EvilDistance.js
- Games/types/Mafia/roles/cards/EvilPairs.js
- Games/types/Mafia/roles/cards/LearnAndLifeLinkToPlayer.js
- Games/types/Mafia/roles/cards/NeighborAlignment.js
- data/modifiers.js
- data/roles.js
Empath, Geologist, Accountant now get info after kills in night order. This is how 99% of players think they work and it just makes more sense.
False Mode Married no longer learns wrong player.
Philosopher goes early in night order so the mind rot works better.
Minor description Improvements
> Very Minor Role Changes

- Games/core/Player.js
- Games/types/Mafia/const/FactionList.js
- Games/types/Mafia/effects/VotingMadness.js
- Games/types/Mafia/roles/Cult/Harpy.js
- Games/types/Mafia/roles/cards/AnonymizeFactionMeeting.js
- Games/types/Mafia/roles/cards/BecomeRedMafia.js
- Games/types/Mafia/roles/cards/GiveVotingMadness.js
- Games/types/Mafia/roles/cards/MeetWithNeighbors.js
- Games/types/Mafia/roles/cards/MeetingFaction.js
- Games/types/Mafia/roles/cards/ModifierLone.js
- Games/types/Mafia/roles/cards/Oblivious.js
- Games/types/Mafia/roles/cards/RemoveModifers.js
- Games/types/Mafia/roles/cards/WinWithIndependentLead.js
- data/modifiers.js
- data/roles.js
- routes/shop.js
Harpy chooses 2 players, If the 2nd player doesn't receive 1/3 of votes from living players, The 1st player, the 2nd player, or Both will die.
> Added Harpy from BOTC

- Games/core/Game.js
- Games/types/Mafia/Event.js
- Games/types/Mafia/Events/CaveIn.js
- Games/types/Mafia/Events/NoEvent.js
- Games/types/Mafia/Events/TimeLoop.js
- Games/types/Mafia/items/CaveIn.js
- Games/types/Mafia/items/EventManager.js
- Games/types/Mafia/roles/cards/CurseWithWordCult.js
- data/contributors.js
Hexer can now hex 4 letter words because people can't read.
> Hexer Change

- Games/core/Game.js
- Games/core/Player.js
- Games/types/Mafia/Event.js
- Games/types/Mafia/Game.js
- Games/types/Mafia/const/ImportantMeetings.js
- Games/types/Mafia/events/SensibleMood.js
- Games/types/Mafia/roles/Cult/Reaper.js
- Games/types/Mafia/roles/Mafia/Gondolier.js
- Games/types/Mafia/roles/cards/Exhausted.js
- Games/types/Mafia/roles/cards/Kill2AndMustRevive.js
- Games/types/Mafia/roles/cards/OffWithTheirHeads.js
- Games/types/Mafia/roles/cards/OneShot.js
- Games/types/Mafia/roles/cards/RedirectAction.js
- Games/types/Mafia/roles/cards/StrongKiller.js
- Games/types/Mafia/roles/cards/StrongModifier.js
- Games/types/Mafia/roles/cards/Suspended.js
- Games/types/Mafia/roles/cards/VampireKill.js
- Games/types/Mafia/roles/cards/Vigicultist.js
- Games/types/Mafia/roles/cards/VillageCore.js
- data/modifiers.js
- data/roles.js
- react_main/src/constants/slangList.js
Added Sensible Mood Event, 1-3 Players will learn their role changed.
Assassin from BOTC as Strong Modifier, Makes Kills performed by the role during the Night, unsavable.
Suspended modifier, Prevents players from using abilities after night 1. also works on events.
One Shot now works Properly with minor rework.
Queen Nerf, Queen no longer has unavoidable beheadings
Added slang from ng(No gun) and Event .
> One Shot Rework, Sensible Mood Event, and Suspended/Strong modifier

- Games/types/Mafia/effects/Insanity.js
- Games/types/Mafia/effects/Tree.js
- Games/types/Mafia/effects/Whistleblown.js
- Games/types/Mafia/items/WeddingRing.js
- Games/types/Mafia/roles/Village/King.js
- Games/types/Mafia/roles/cards/BroadcastMessage.js
- Games/types/Mafia/roles/cards/ContactByRole.js
- Games/types/Mafia/roles/cards/ControlPuppet.js
- Games/types/Mafia/roles/cards/CountEvilVotes.js
- Games/types/Mafia/roles/cards/ForceSplitDecision.js
- Games/types/Mafia/roles/cards/FungalSpores.js
- Games/types/Mafia/roles/cards/MagusGame.js
- Games/types/Mafia/roles/cards/MakeVisitorsInsane.js
- Games/types/Mafia/roles/cards/MindRotEveryoneOnEvilCondemn.js
- Games/types/Mafia/roles/cards/WinIfRivalIsDead.js
- data/roles.js
> Removed Life Link from Bride and Santista description Improvment

- Games/core/Player.js
- Games/types/Mafia/effects/Fiddled.js
Reverts UltiMafia/Ultimafia#1772
> Revert "Fiddle change"

- Games/core/Player.js
- Games/core/Role.js
- Games/types/Mafia/Game.js
- Games/types/Mafia/Information.js
- Games/types/Mafia/Role.js
- Games/types/Mafia/effects/FavorableMode.js
- Games/types/Mafia/effects/TrueMode.js
- Games/types/Mafia/effects/UnfavorableMode.js
- Games/types/Mafia/information/AlignmentInfo.js
- Games/types/Mafia/information/BinaryAlignmentInfo.js
- Games/types/Mafia/information/RoleInfo.js
- Games/types/Mafia/roles/cards/AppearAsRandomEvil.js
- Games/types/Mafia/roles/cards/FalseModifier.js
- Games/types/Mafia/roles/cards/FavorableModifier.js
- Games/types/Mafia/roles/cards/LearnAlignment.js
- Games/types/Mafia/roles/cards/LearnRole.js
- Games/types/Mafia/roles/cards/ReadMind.js
- Games/types/Mafia/roles/cards/TrueModifier.js
- Games/types/Mafia/roles/cards/UnfavorableModifier.js
- Games/types/Mafia/roles/cards/VampireAppearAsRoles.js
- data/modifiers.js
Miller/Vampire now show with Modifiers
> Miller/Vampire Fix 

- Games/types/Mafia/roles/Independent/Astrologer.js
- Games/types/Mafia/roles/Independent/Gambler.js
- Games/types/Mafia/roles/cards/ChallengeTarget.js
- Games/types/Mafia/roles/cards/WinIfPairedLoversAlive.js
> Gambler fix

- Games/types/Mafia/information/BinaryAlignmentInfo.js
- Games/types/Mafia/roles/cards/WinIfNightKilled.js
- data/roles.js
Joker can win if Dawn is occurring.
Added a Special Interaction between Joker and Assassin to make Joker more like it's Split Decision version.
> Joker fixes and Cop report change reverted for real this time

- Games/core/Player.js
- Games/types/Mafia/Information.js
- Games/types/Mafia/information/EvilPlayerInfo.js
- Games/types/Mafia/roles/cards/OpenTheDoor.js
Tested with Mafia, Cult, Cop, and Mistress
Graveyard Meeting still exists and Restless also still works
Add Mistress info file
> Fixed Roles being to act when dead

- Games/types/Mafia/Information.js
- Games/types/Mafia/information/GoodOrEvilRoleInfo.js
- Games/types/Mafia/information/OneOf3RolesInfo.js
- Games/types/Mafia/information/RoleInfo.js
- Games/types/Mafia/roles/cards/GlobalModifier.js
- Games/types/Mafia/roles/cards/LearnGoodAndEvilRole.js
- Games/types/Mafia/roles/cards/NightComedian.js
- data/modifiers.js
Global Modifier makes roles target everyone, Only works for roles that choose 1 player.
Comedian changes- In closed setups comedian jokes can show excess roles. (Comedian will only show in play roles in non-closed setups). Comedian jokes will no longer contain celebrity or exposed roles unless the player being shown in the joke has that role.
Diviner changes- Same as comedian but with info instead of jokes.
> Comedein and Diviner info Files and Global Modifier

- Games/types/Mafia/Information.js
- Games/types/Mafia/information/ItemInfo.js
- Games/types/Mafia/information/WatcherRoleInfo.js
- Games/types/Mafia/roles/cards/ConvertToChosenRole.js
- Games/types/Mafia/roles/cards/ConvertToCultists.js
- Games/types/Mafia/roles/cards/KillCultistsOnDeath.js
- Games/types/Mafia/roles/cards/LearnVisitors.js
- Games/types/Mafia/roles/cards/LearnVisitorsRole.js
- Games/types/Mafia/roles/cards/SnoopItems.js
- Games/types/Mafia/roles/cards/SwapRolesOnce.js
- Games/types/Mafia/roles/cards/WatchPlayerRole.js
- Games/types/Mafia/roles/cards/WinSwap.js
- data/roles.js
- package-lock.json
- react_main/src/pages/Game/MafiaGame.jsx
Broker now works with day start
SC can now only swap once
Info Files for Role Watching roles and Snoop
Mi-Go can now turn players into roles of other alignments (Player alignment will not change)
> Broker+Snake Charmer bug fixes + more info files + Mi-Go Buff

- Games/types/Mafia/information/GuessRoleInfo.js
- Games/types/Mafia/roles/cards/BecomeAlignmentOfVisitors.js
- Games/types/Mafia/roles/cards/GuessFiveRoles.js
- Games/types/Mafia/roles/cards/GuessRole.js
- Games/types/Mafia/roles/cards/WinSwap.js
- data/roles.js
- package-lock.json
Manhunter/Bondsman now must choose from everyrole in the setup instead of just the in play roles.
Analyst-  'On their 1st day if an Analyst makes a guess in chat following this structure "I will analyze if (Player Name) is (Role Name)".',
"The Analyst will learn how many guesses were correct during the night.",
"The Analyst may only make 5 guesses.",
> Manhunter/Bondsman/Analyst  info files and changes

- Games/types/Mafia/Information.js
- Games/types/Mafia/information/AllReportsInfo.js
- Games/types/Mafia/information/ExcessRolesInfo.js
- Games/types/Mafia/information/ReportsInfo.js
- Games/types/Mafia/information/VisitsAndReportsInfo.js
- Games/types/Mafia/roles/cards/CompareBooleanTrack.js
- Games/types/Mafia/roles/cards/CountWrongReveals.js
- Games/types/Mafia/roles/cards/Dream.js
- Games/types/Mafia/roles/cards/GiveSuperpowers.js
- Games/types/Mafia/roles/cards/GuessAdversaryConvert.js
- Games/types/Mafia/roles/cards/GuessAdversaryKill.js
- Games/types/Mafia/roles/cards/GuessFiveRoles.js
- Games/types/Mafia/roles/cards/LearnEvilDeadCount.js
- Games/types/Mafia/roles/cards/LearnIfRoleChanged.js
- Games/types/Mafia/roles/cards/ModifierLoud.js
- Games/types/Mafia/roles/cards/NightCaroler.js
- Games/types/Mafia/roles/cards/NightComedian.js
- Games/types/Mafia/roles/cards/ReceiveAllReports.js
- Games/types/Mafia/roles/cards/ReceiveReports.js
- Games/types/Mafia/roles/cards/RevealNameToTarget.js
- Games/types/Mafia/roles/cards/RevealRoleToTarget.js
- Games/types/Mafia/roles/cards/WatchPlayer.js
- Games/types/Mafia/roles/cards/WatchPlayerBoolean.js
- Games/types/Mafia/roles/cards/WatchPlayerRole.js
- data/roles.js
Added Info files for Journalist, Pathologist, and housekeeper
Fixed Guiser guising Analyst breaking game
Fixed Hider/seeker getting converted breaking game.
> More Info Files and Bug Fixes

- Games/types/LiarsDice/Game.js
- Games/types/LiarsDice/items/Gun.js
- Games/types/LiarsDice/items/Snooping.js
- Games/types/LiarsDice/roles/Liars/Graverobber.js
- Games/types/LiarsDice/roles/Liars/Sniper.js
- Games/types/LiarsDice/roles/Liars/Snoop.js
- Games/types/LiarsDice/roles/Liars/Thief.js
- Games/types/LiarsDice/roles/cards/GainDiceOnCorrectLieCall.js
- Games/types/LiarsDice/roles/cards/GainDiceOnCorrectSpotOnCall.js
- data/roles.js
- react_main/src/css/roles.css
- react_main/src/pages/Game/LiarsDiceGame.jsx
Thief: Gains 1 Dice when they successfully call a Lie.
Graverobber: Gains 1 Dice when they successfully call a Spot On.
Sniper:  Once per game, Can shoot a player making them lose 1 dice.
That player will not learn which dice they lost until the next turn.
Snoop: "Once per game, Can learn what dice a player has."
> Added Liars Dice Roles

- Games/types/LiarsDice/Game.js
- Games/types/LiarsDice/const/ImportantMeetings.js
- Games/types/LiarsDice/items/Gun.js
- Games/types/LiarsDice/items/Microphone.js
- Games/types/LiarsDice/items/ProposalOffer.js
- Games/types/LiarsDice/items/Propose.js
- Games/types/LiarsDice/items/Spying.js
- Games/types/LiarsDice/roles/Liars/Soldier.js
- Games/types/LiarsDice/roles/Liars/Suitress.js
- Games/types/LiarsDice/roles/cards/GainDiceOnCorrectLieCall.js
- Games/types/LiarsDice/roles/cards/GainDiceOnCorrectSpotOnCall.js
- Games/types/LiarsDice/roles/cards/TakeNoDiceOnLieCall.js
- Games/types/Mafia/Game.js
- Games/types/Mafia/Information.js
- Games/types/Mafia/information/GuessPlayerNeighborRoleInfo.js
- Games/types/Mafia/information/GuessPlayerVisitRoleInfo.js
- Games/types/Mafia/information/GuessPlayerVisitorRoleInfo.js
- Games/types/Mafia/information/PenguinInfo.js
- Games/types/Mafia/roles/cards/LearnAboutPlayerAndRole.js
- Games/types/Mafia/roles/cards/WaddleAndTellSecret.js
- data/roles.js
- db/schemas.js
- react_main/src/css/roles.css
- react_main/src/pages/User/Profile.jsx
- react_main/src/pages/User/User.jsx
- routes/report.js
- routes/user.js
Added Soldier to Liar's Dice, Soldier gains a gun when calling a lie instead of taking a dice from bidder.
Added Suitress to Liar's Dice, Can propose to a player. If they accept the suitress and that player gain a dice. If they reject the suitress loses a dice.
> 2 more Liar dice roles and Penguin Info File

- Games/core/Player.js
- Games/core/Role.js
- Games/types/Mafia/information/RevealInfo.js
- Games/types/Mafia/items/Crystal.js
- Games/types/Mafia/items/Drama.js
- Games/types/Mafia/items/WeddingRing.js
- Games/types/Mafia/roles/cards/CondemnReveal.js
- Games/types/Mafia/roles/cards/PGRevealRole.js
- Games/types/Mafia/roles/cards/RevealTargetOnDeath.js
- Games/types/Mafia/roles/cards/SleepWalk.js
Sleepwalker can no longer self visit.
> Reveal Info File + SW change

- Games/core/Game.js
- Games/core/Meeting.js
- Games/core/PostgameMeeting.js
- db/schemas.js
- react_main/src/css/user.css
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/User/Profile.jsx
- react_main/src/pages/User/User.jsx
- routes/user.js
Normal profile:
Cramped profile:
Miniprofile:
Happens very similarly to upvoting or downvoting a comment, except it's tied to a user. Every single vote a user does for another is recorded separately in the database, but votes are not visible to other users.
When a game is ranked or competitive, a kudos can be voted on to be awarded in the postgame meeting. When the lobby closes (after all players leave or 2 minutes, whichever comes first), the vote is calculated and awards it to the winner.
Ties will be randomly awarded between the highest scorers, and games with no kudos votes will give no kudos. You can see who received the kudos by reviewing the game after it closes.
- Fixed NameWithAvatar always querying for the user's profile, this is fixed to only happen when it's needed in games …
> Added kudos and karma, resolves #1509

- Games/types/WackyWords/Game.js
- Games/types/WackyWords/data/decisions.js
- Games/types/WackyWords/roles/Town/Gambler.js
- Games/types/WackyWords/roles/cards/ResponseGiver.js
- Games/types/WackyWords/roles/cards/TownCore.js
- data/roles.js
- react_main/src/css/roles.css
- react_main/src/pages/Learn/LearnWackyWords.jsx
We will need to add more decisions to decisions.js at some point
> Wacky Decisions

- react_main/src/css/user.css
- react_main/src/pages/User/Profile.jsx
This whole page needs an overhaul
> bad fix: css mobile disables karma/kudos box

- react_main/src/pages/User/PieChart.jsx
Minipopover is now hidden in game if the user has chosen to hide their statistics.
> now hides the piechart if the user stats are hidden

- Games/core/Game.js
- Games/core/Meeting.js
- Games/core/Player.js
- Games/types/Mafia/events/Vaccination.js
- Games/types/Mafia/items/Blobbed.js
- Games/types/Mafia/roles/cards/ChoirOfRoles.js
- Games/types/Mafia/roles/cards/IfVotedForceCondemn.js
- Games/types/Mafia/roles/cards/NightBlobber.js
- data/items.js
- data/roles.js
- react_main/src/constants/commandList.js
Provide the Item/Modifier description when used.
> /item and /modifier

- Games/types/Mafia/roles/cards/WinByStealingClovers.js
- Games/types/Mafia/roles/cards/WinIfTimebombKillsThree.js
- Games/types/Mafia/roles/cards/WinWithTwoGambleWins.js
I think Anarchist winning with 1 bomb is unfair so I made Anarchist scale at 2/3/4. It can be changed by editing the numbers if you disagree.
> https://github.com/UltiMafia/Ultimafia/issues/1855 Done

- Games/core/Game.js
- Games/core/Message.js
- Games/core/Player.js
- Games/core/Quote.js
- Games/core/User.js
- Games/games.js
- data/constants.js
- db/schemas.js
- lib/Utils.js
- modules/redis.js
- react_main/src/components/Basic.jsx
- react_main/src/components/EmotePicker.jsx
- react_main/src/components/Emotes.jsx
- react_main/src/components/Form.jsx
- react_main/src/css/settings.css
- react_main/src/pages/Community/Moderation.jsx
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/User/Settings.jsx
- routes/game.js
- routes/mod.js
- routes/shop.js
- routes/user.js
Here are my notes from when I was developing:
```
Ensure:
[x] - custom emotes work in active games
[x] - custom emotes work in quotes
[x] - custom emotes work in game reviews
[x] - custom emotes aren't usable by other users
[x] - custom emotes override site emotes if name overlaps
[x] - custom emotes are properly created and deleted from settings
[x] - custom emote size is 20x20 px
[x] - custom emotes retain transparency
[x] - custom emotes don't lose too much quality
[x] - custom emotes have a max length for their name (25 chars)
[x] - custom emotes are populated in the emote panel
[x] - custom emotes don't work during anonymous games
[x] - custom emotes can't be seen after a mod clears them
[x] - custom emotes can't be seen after a mod clears all content for a user
[x] - custom emotes …
```
> Added custom emotes, resolves #1523

- Games/types/Mafia/effects/SpeakOnlyWhispers.js
https://github.com/UltiMafia/Ultimafia/issues/1628
> Librarian Fix

- Games/types/Mafia/items/Room.js
- Games/types/Mafia/items/RoomLeader.js
Klutzy can no longer drop Being in a room
> Assassin Fix

- Games/types/Mafia/Winners.js
- Games/types/Mafia/roles/cards/WinByCondemning.js
- Games/types/Mafia/roles/cards/WinIfNightKilled.js
- Games/types/Mafia/roles/cards/WinIfShot.js
- data/modifiers.js
- data/roles.js
Removed Joker + Assassin Special Interaction
> Standardize Joints on non-hostile 3rds

- Games/games.js
- Games/types/Mafia/Player.js
- Games/types/Mafia/items/Trollbox.js
- Games/types/Mafia/roles/cards/Provocative.js
- data/items.js
- data/modifiers.js
I also tested that trollbox messages work properly with assassin and anonymous games.
> Added provocative modifier - useful for fool and executioner

- Games/types/Mafia/Game.js
- Games/types/Mafia/Player.js
- Games/types/Mafia/roles/cards/ClownAround.js
- Games/types/Mafia/roles/cards/MustRoleShareWithVip.js
- Games/types/Mafia/roles/cards/WinIfAllVanilla.js
- Games/types/Mafia/roles/cards/WinIfMafiaWon.js
- Games/types/Mafia/roles/cards/WinIfVillageWon.js
- Games/types/Mafia/roles/cards/WinWithIndependentLead.js
- data/constants.js
- data/roles.js
- react_main/src/constants/Achievements.js
> Min Maf Count fix

- Games/types/Ghost/roles/Host/Host.js
- Games/types/Ghost/roles/cards/RevealAllRoles.js
- react_main/src/pages/User/Profile.jsx
For Rangoon's Ghost Tournament
> Host can see other players' roles in Ghost

- Games/core/Game.js
- Games/types/Mafia/Player.js
- Games/types/Mafia/achievements/CultVictory.js
- Games/types/Mafia/achievements/IndependentVictory.js
- Games/types/Mafia/achievements/MafiaVictory.js
- Games/types/Mafia/achievements/ProAnalyst.js
- Games/types/Mafia/achievements/SheriffShootEvil.js
- Games/types/Mafia/achievements/VillageVictory.js
- Games/types/Mafia/information/GuessRoleInfo.js
- react_main/src/pages/Play/CreateSetup/CreateMafiaSetup.jsx
- react_main/src/pages/Play/Host/HostAcrotopia.jsx
- react_main/src/pages/Play/Host/HostDefaults.js
- react_main/src/pages/Play/LobbyBrowser/RecentlyPlayedSetups.jsx
Fixed Sheriff not getting achievement if converted after.
Fixed Magus getting Village Victory instead of Independent victory.
Fixed Analyst being able to guess self as Analyst 5 times to get Achievement.
Talking Dead- Lets dead talk.
> Achievement Fixes and Talking Dead Game Setting

- Games/core/Player.js
- Games/types/Mafia/roles/cards/SelectHostAndDie.js
Parasite no longer shows as dead when controlling host.
Completes
https://github.com/UltiMafia/Ultimafia/issues/1871
> Parasite Buff

- Games/types/Mafia/items/Blade.js
- Games/types/Mafia/items/Revolver.js
- Games/types/Mafia/roles/Independent/Dragoon.js
- Games/types/Mafia/roles/cards/Duel.js
- Games/types/Mafia/roles/cards/RevolverGiver.js
- Games/types/Mafia/roles/cards/WinByRevolverKills.js
- Games/types/Mafia/roles/cards/WinIfWonDuel.js
- data/Achievements.js
- data/constants.js
- data/items.js
- data/roles.js
- react_main/src/constants/Achievements.js
Does the thing with the Revolver.
> Dragoon Role

- Games/core/Role.js
- Games/types/Mafia/Player.js
- Games/types/Mafia/Role.js
- Games/types/Mafia/effects/Unveggable.js
- Games/types/Mafia/items/Blade.js
- Games/types/Mafia/roles/cards/ChoirOfRoles.js
- Games/types/Mafia/roles/cards/IfVotedForceCondemn.js
- Games/types/Mafia/roles/cards/WinWithFaction.js
- data/constants.js
If a role is an alignment other then it's default alignment it will show that on death.
> Show true faction on death + Princess dusk fix

- Games/types/CardGames/DrawDiscardPile.js
- Games/types/CardGames/Game.js
- Games/types/CardGames/const/Decks.js
- react_main/src/pages/Game/CardGamesGame.jsx
- react_main/src/pages/Play/Host/HostCardGames.jsx
Fixed SmallBlind and BigBlind sometimes being the same player.
Fixed Straights not working
added Community Card UI
now shows when a player folds
now shows round number and game phase
> Card Games fixes

- react_main/src/css/gameCardGames.css
- react_main/src/pages/Game/CardGamesGame.jsx
Fixed UI bug with dice being cards
> Liars Dice Hotfix

- Games/types/Mafia/roles/cards/WinWithFaction.js
Now no one should win when everyone is dead.
> Fixed Mafia Winning when All players are dead

- Games/types/Mafia/roles/cards/MustAct.js
- Games/types/Mafia/roles/cards/Nonconsecutive.js
- Games/types/Mafia/roles/cards/VisitOnlyDead.js
- data/modifiers.js
Morbid now works but It also effects items.
Proactive makes it so you must act in secondary meetings
> Must Act Modifier + Morbid Now works*

- Games/types/Mafia/events/Moonshine.js
- Games/types/Mafia/events/OminousWarning.js
- Games/types/Mafia/roles/cards/AppearAsVanillaEvil.js
- data/modifiers.js
- data/roles.js
Event that gives Whiskey
Event that gives Knife
Suspect Modifier for Windsy- Appears as a Vanilla Evil Role from the setup when investigated or condemned. Appears as their real role on death. (Solves issue with the new Miller making Basic Variant not work).
> 2 Item Events + Suspect Modifier

- data/constants.js
- db/schemas.js
- modules/periodic.js
- react_main/src/css/game.css
- react_main/src/css/user.css
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/User/Profile.jsx
- routes/game.js
- routes/shop.js
- routes/user.js
For #1809
Added a button to the game review screen where users, if they've purchased the capability from the shop, can archive a game. Archived games are exempt from expiration and appear on the user's profile. Users can "unarchive" games from their profile. Unarchiving a game that is beyond its expiration date will cause it to be deleted on the next sweep.
Eventually I would like to add the ability to edit the description of an archived game, but I'm not doing it for the first swing at it.
> Added archived games functionality

- Games/core/Player.js
- Games/types/Mafia/achievements/DeclareMagusAsEvil.js
- Games/types/Mafia/achievements/GrannyKills.js
- Games/types/Mafia/achievements/HunterKill.js
- Games/types/Mafia/achievements/MillerTowntell.js
- Games/types/Mafia/achievements/PedagoguePedagogue.js
- Games/types/Mafia/achievements/ShrinkSaveTwice.js
- Games/types/Mafia/achievements/SilencerSilence2PR.js
- Games/types/Mafia/achievements/TrackerCheck.js
- Games/types/Mafia/achievements/UndertakerCleanPR.js
- Games/types/Mafia/achievements/WatcherCheck2.js
- Games/types/Mafia/roles/cards/NightConvertBlocker.js
- Games/types/Mafia/roles/cards/VillageCore.js
- data/Achievements.js
- modules/periodic.js
- react_main/src/constants/Achievements.js
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/User/Profile.jsx
- react_main/src/pages/User/User.jsx
- routes/game.js
- routes/user.js
Fixed Vest not working after being converted?
Update the Checklist at https://github.com/UltiMafia/Ultimafia/issues/1834
Eyewitness: {
ID: "Mafia31",
internal: ["WatcherCheck2"],
description:
"As Watcher, see Evil players visiting twice and survive until the end of the game.",
reward: 30,
roles: ["Watcher"],
},
"On the Trail": {
ID: "Mafia32",
internal: ["TrackerCheck"],
description: "As Tracker, track a player who visits you.",
reward: 10,
roles: ["Tracker"],
},
"I'm Towntelling!": {
ID: "Mafia33",
internal: ["MillerTowntell"],
description:
"As Miller, survive and win after being checked by a Cop or Detective.",
reward: 20,
roles: ["Miller"],
},
"So Below": {
ID: "Mafia34",
internal: ["DeclareMagusAsEvil"],
description:
"As a Mafia or Cult role, convince the Village to Declare a Magus …
> 10 more Achievement + bug Fixes

- react_main/src/css/game.css
- react_main/src/pages/Game/Game.jsx
As seen in the discord's design dev channel
> Added vote counters to village condemn meeting

- Games/core/Game.js
- Games/types/Mafia/events/HauntedHouse.js
- data/roles.js
- modules/redis.js
- react_main/src/pages/Fame/Fame.jsx
- react_main/src/pages/Fame/Leaderboard.jsx
- routes/user.js
I have no Idea why achievements or Win Rate are not working
It also only shows Online Users
Haunted House now prioritizes giving to players being Attacked
> Scoreboard working for Kudos and Karma + Haunted House Change

- Games/types/CardGames/const/Decks.js
- Games/types/Mafia/events/HauntedHouse.js
- Games/types/Mafia/roles/cards/RoleDisguiser.js
- data/contributors.js
Actress goes before Info roles in night Order
> Actress Fix

- Games/core/Meeting.js
- Games/core/PostgameMeeting.js
- Games/types/Mafia/items/CaveIn.js
- Games/types/Mafia/meetings/Village.js
- react_main/src/pages/Game/Game.jsx
This just makes it so that you can easily turn vote counters on and off for the meetings that you want. I added them to cave in since it's basically the same as a village condemnation meeting
> Added a flag to turn vote counters on for village, CaveIn meetings

- react_main/src/pages/Game/Game.jsx
users may also click on no one to vote it:
> Added no one to the selectables in votes if applicable, plus counter

- Games/types/Mafia/roles/Mafia/Hacker.js
- Games/types/Mafia/roles/Village/Modder.js
- Games/types/Mafia/roles/cards/AddRandomModifier.js
- Games/types/Mafia/roles/cards/Blinder.js
- Games/types/Mafia/roles/cards/FalseModifier.js
- Games/types/Mafia/roles/cards/ModifierTelepathic.js
- Games/types/Mafia/roles/cards/NightConvertBlocker.js
- Games/types/Mafia/roles/cards/Silencer.js
- Games/types/Resistance/roles/Spies/Assassin.js
- Games/types/Resistance/roles/cards/AssassinGuess.js
- Games/types/Resistance/roles/cards/SpyCore.js
- Games/types/Resistance/roles/cards/TeamCore.js
- data/modifiers.js
- data/roles.js
- react_main/src/css/roles.css
Modder- Each night chooses a player, That player gains a random modifier.
Hacker- same as modder but mafia.
telepathic now works
> Modder/Hacker roles + telepathic fix

- react_main/src/components/Setup.jsx
- react_main/src/css/game.css
- react_main/src/css/setup.css
- react_main/src/css/shiny.css
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/Play/Host/HostBrowser.jsx
- react_main/src/pages/Play/LobbyBrowser/GameRow.jsx
- react_main/src/pages/Play/LobbyBrowser/LobbyBrowser.jsx
- react_main/src/pages/Play/LobbyBrowser/PlayerCount.jsx
- react_main/src/pages/Play/LobbyBrowser/RecentlyPlayedSetups.jsx
- Fixed ellipses appearing one thing too early in setup display
- Cleaned up a bunch of unused CSS classes
- Added background color to ingame setup component
- Fixed no spectating icon making rows tall
- Added metallic gold background to comp lobby row stub
- hid the developer fill button if on mobile
> UI touchups

- react_main/src/pages/Game/Game.jsx
> Tweaked visuals for "special" targets, added *magus special target to UI

- .gitignore
- Games/core/Game.js
- db/schemas.js
- react_main/src/components/Popover.jsx
- routes/game.js
If two profiles have the same name one will be removed from the pool.
To use multiple decks a comma after the first deck ID.
> Use Multiple Decks at same time

- Games/core/Game.js
- data/constants.js
- modules/redis.js
- react_main/src/pages/User/UserNotifications.jsx
also lowers refresh interval to 23 hours
> Added a tooltip indicator to red hearts for when they will refresh

- modules/periodic.js
- react_main/src/css/game.css
- react_main/src/hooks/useLongPress.jsx
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/Game/GhostGame.jsx
- react_main/src/pages/Game/MafiaGame.jsx
- react_main/src/pages/Game/ResistanceGame.jsx
- react_main/src/pages/User/User.jsx
see discord design-dev channel for video of changes
> Added pinned messages, reworked rendering of messages for ingame chat UI

- Games/types/CardGames/Action.js
- Games/types/CardGames/Card.js
- Games/types/CardGames/DrawDiscardPile.js
- Games/types/CardGames/Game.js
- Games/types/CardGames/Item.js
- Games/types/CardGames/Meeting.js
- Games/types/CardGames/Player.js
- Games/types/CardGames/Role.js
- Games/types/CardGames/Winners.js
- Games/types/CardGames/roles/cards/WinIfLastAlive.js
- Games/types/Mafia/roles/Mafia/Gramps.js
- Games/types/Mafia/roles/Village/Lifeguard.js
- Games/types/Mafia/roles/Village/Riflemaster.js
- Games/types/Mafia/roles/cards/BecomeRoleForNight.js
- Games/types/Mafia/roles/cards/BecomeRoleInstantly.js
- Games/types/Mafia/roles/cards/CurseVote.js
- Games/types/Mafia/roles/cards/VoteToBlockVotes.js
- data/modifiers.js
- data/roles.js
- react_main/src/components/Popover.jsx
- react_main/src/pages/Play/Host/HostCardGames.jsx
- react_main/src/pages/Play/Host/HostDefaults.js
- routes/game.js
Lifeguard- All votes for whoever a Lifeguard is voting for do not count.
Monkey/Ape/Doppelganger- No longer add Dusk to the setup.
Max Rounds Game Setting for Texas Hold Em
After X rounds the player with the most chips wins.
Also Riflemaster role
> Lifeguard Role + Monkey/Ape/Doppelganger changes + New Game Setting for texas hold em

- react_main/src/pages/Game/MafiaGame.jsx
I tested that each track worked. Feel free to change the mappings however feels best.
> Added hooks and mappings for night music

- react_main/src/components/Roles.jsx
site wasn't loading for me because my setting was empty
> Added a null check for if user's roleskin setting is null

- react_main/src/css/game.css
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/User/User.jsx
> Added back vertical aligned mode, fixed timestamps not showing on mobile

- db/schemas.js
- react_main/src/Main.jsx
- react_main/src/css/main.css
- react_main/src/css/nav.css
- react_main/src/pages/Play/LobbyBrowser/DailyChallengeDisplay.jsx
- react_main/src/pages/Play/LobbyBrowser/GameRow.jsx
- react_main/src/pages/Play/LobbyBrowser/LobbyBrowser.jsx
- react_main/src/pages/Play/LobbyBrowser/PlayerCount.jsx
- react_main/src/pages/Play/LobbyBrowser/RecentlyPlayedSetups.jsx
- react_main/src/pages/User/UserNotifications.jsx
- react_main/src/services/gameService.jsx
- routes/game.js
Other changes:
- Fixed not being able to rehost games that were anonymous
- Fixed recently played setups not refreshing when lobby changes (had to refresh)
> Switched UI for lobby browser to 2 panel layout, also fixed #2073

- react_main/src/css/join.css
- react_main/src/pages/Play/LobbyBrowser/LobbyBrowser.jsx
- react_main/src/pages/Play/LobbyBrowser/PlayerCount.jsx
> Tweaked player count UI style

- data/contributors.js
guess who kept forgetting to add fortune teller to his contributor page
> Update art contributor

- react_main/src/css/join.css
- react_main/src/pages/Play/LobbyBrowser/GameRow.jsx
- react_main/src/pages/Play/LobbyBrowser/RecentlyPlayedSetups.jsx
- Fixed inconsistent player count bar color
- Fixed game icons appearing in the profile
- Fixed overflowing recently played setups component
> Fixed minor UI bugs

- Games/core/Card.js
- Games/core/Player.js
- Games/core/Role.js
- data/roles.js
- package-lock.json
Modifiers that modifier when an action can be done now correctly work together.
> X Shot/Restless/delayed/even/odd/etc Fix

- Games/types/Mafia/Action.js
- Games/types/Mafia/Information.js
- Games/types/Mafia/effects/Virus.js
- Games/types/Mafia/roles/Cult/PlagueDoctor.js
- Games/types/Mafia/roles/Cult/Skinwalker.js
- Games/types/Mafia/roles/cards/MakeKillHidden.js
- Games/types/Mafia/roles/cards/PlagueStarter.js
- data/roles.js
- package-lock.json
Skinwalker is a Cult version of Imposter.
Plague Doctor-
On their first night, choose a player to Infect with a Virus.
Each night the infected players will infect their neighbors.
Players who have been infected for 2 nights will die.
Ninja no longer makes all mafia not visit
> Plague Doctor and Skinwalker roles + Ninja fix

- Games/types/Mafia/roles/Village/Damsal.js
- Games/types/Mafia/roles/Village/Hero.js
- Games/types/Mafia/roles/cards/GuessDamsal.js
- Games/types/Mafia/roles/cards/LoseIfGuessed.js
- data/roles.js
Huntsmen as Hero: 
alignment: "Village",
"Attempts to guess the identity of the Damsal each night.",
"Converts them to a Random non-banished Village Role if Correct.",
"Forces a Damsal to Spawn in closed setups.",
Damsal:
alignment: "Village",
'If the first Evil Player to say "I think the Damsel is (Player Name)" during the day is correct, Mafia and Cult win.',
"All Mafia and Cult players learn if a Damsel is in the game.",
> 2 botc roles

- Games/core/Game.js
- Games/core/Player.js
- Games/types/Daily/Play3Games.js
- Games/types/Mafia/items/Blade.js
- Games/types/Mafia/items/Drama.js
- Games/types/Mafia/items/ExtraCondemn.js
- Games/types/Mafia/items/FishingRod.js
- Games/types/Mafia/items/Gamble.js
- Games/types/Mafia/items/HostGrantImmuity.js
- Games/types/Mafia/items/HostPlayerPoll.js
- Games/types/Mafia/items/Notebook.js
- Games/types/Mafia/items/Revolver.js
- Games/types/Mafia/items/Room.js
- Games/types/Mafia/items/Timebomb.js
- Games/types/Mafia/items/WeddingRing.js
- Games/types/Mafia/roles/Village/Fisherman.js
- Games/types/Mafia/roles/cards/GiveFishingRod.js
- Games/types/Mafia/roles/cards/Magnetic.js
- Games/types/Mafia/roles/cards/VillageCore.js
- data/DailyChallenge.js
- data/items.js
- data/modifiers.js
- data/roles.js
- react_main/src/constants/DailyChallenge.js
Magnetic- If possible, night kills will be redirected onto this player if someone with the same alignment as them is targeted.
Day Actions no longer prevent day from ending (Except for Anarchist bomb, Dragoon Revolver, and Suitress/Drama Queen accept proposal)
Players will no longer veg for failing to do day actions (Except for Anarchist bomb, Dragoon Revolver, and Suitress/Drama Queen accept proposal)
Made the play 3 games daily challenge into play 3 unranked games to encourage more unranked games. (Will likely have no effect).
> Day Actions changes + Magnetic modifier

- react_main/package-lock.json
- react_main/package.json
- react_main/src/Main.jsx
- react_main/src/pages/Play/LobbyBrowser/RecentlyPlayedSetups.jsx
no more people wondering what their empty screen means
> Added error boundary for frontend errors

- react_main/public/index.html
- react_main/src/Main.jsx
- react_main/src/components/HostGameDialogue.jsx
- react_main/src/index.jsx
- react_main/src/pages/User/Profile.jsx
- routes/mod.js
- Fixed flash of white for dark mode users when reloading page
- Fixed theme being out of sync for new users whose browser is using the system theme
- Fixed banner being larger than 900px
- Fixed error that occurred when secret dictator was being hosted
> Various UI fixes

- react_main/src/components/Roles.jsx
- react_main/src/css/game.css
- react_main/src/pages/Game/AcrotopiaGame.jsx
- react_main/src/pages/Game/BattlesnakesGame.jsx
- react_main/src/pages/Game/CheatGame.jsx
- react_main/src/pages/Game/ConnectFourGame.jsx
- react_main/src/pages/Game/Game.jsx
- react_main/src/pages/Game/GhostGame.jsx
- react_main/src/pages/Game/JottoGame.jsx
- react_main/src/pages/Game/LiarsDiceGame.jsx
- react_main/src/pages/Game/MafiaGame.jsx
- react_main/src/pages/Game/ResistanceGame.jsx
- react_main/src/pages/Game/SecretDictatorGame.jsx
- react_main/src/pages/Game/TexasHoldEmGame.jsx
- react_main/src/pages/Game/WackyWordsGame.jsx
- Fixed popover getting stuck
- Moved player count into player list title
- Improved spacing
- Tweaked panels on mobile to allow adjacent panels to be visible
- Fixed unresolved action count showing when reviewing
> ingame UI touchups

- Games/core/PregameReadyMeeting.js
- react_main/src/pages/Game/Game.jsx
Updates to game inputs should limit vegging from being Jinx and not knowing how it works
> feat(UI): remade ActionText in MUI

- Games/core/Meeting.js
- Games/core/Player.js
- Games/core/Quote.js
- Games/types/Mafia/effects/Cursed.js
- Games/types/Mafia/effects/CursedCult.js
- Games/types/Mafia/effects/WordTracker.js
- react_main/src/pages/Game/Game.jsx
Jinx, Hexer, and that one other mafia role can now trigger on quotes.
resolves:
https://github.com/UltiMafia/Ultimafia/issues/37
> Quote nerf

- Games/core/PregameMeeting.js
- db/schemas.js
- react_main/src/Main.jsx
- react_main/src/pages/Game/Game.jsx
- Made misfortune hidden by default
- Fixed pregame being considered a voting meeting
- Fixed action counter including non-voting meetings and meetings that the member can't vote in
- Fixed spiderweb GIF not loading for eventual halloween site theme
> Fixed some misc bugs

- scripts/mongo/migrate-ghost-reverse.js
- scripts/mongo/migrate-ghost.js
Run with care, set the DRY_RUN to true first in the script. Ran using mongosh's `load('/scripts/migrate-ghost.js')`
> Added ghost migration scripts

- Games/core/Meeting.js
- Games/types/Mafia/items/OuijaBoard.js
- Games/types/Mafia/items/Summon.js
- Games/types/Mafia/roles/cards/GhostGame.js
- Games/types/Mafia/roles/cards/ShooterFramer.js
- data/roles.js
- react_main/src/pages/Game/Game.jsx
- scripts/mongo/migrate-ghost-reverse.js
- scripts/mongo/old-migration-scripts/migrate-ghost.js
Ghost no longer randomly breaks
Ghost give clue can handle players dying before giving clue.
Added word reveal at the end of the game.
> Ghost Fixes + Mafia role descriptions

- data/contributors.js
- data/donors.js
Updating name for Aleph to Megido.
> Update Contrib and Donor
