UltiMafia/Ultimafia

.github/workflows/prettier.yml
- Use `bash ` instead of `sh ` for prettier workflow (bash scripts support `[[ ]]` commands.
- Hopefully this is the last one :')
=> Fix prettier workflow

react_main/src/pages/User/Profile.jsx
Following up on discussion from [discord](https://discord.com/channels/1102713221711925339/1117728202366918717/1124867794186534982):
Currently pie charts are calculating losses from `totalGames`, which includes games that were abandoned by others: 
`losses = totalGames - wins.count - abandons.total` which basically just includes abandoned games in losses.
Within stats, `totalGames` is recalculated (as `totalGamesUnabandoned`) as `wins.total + abandons.total`.
totalGamesUnabandoned - wins - abandons => `(wins.total + abandons.total) - wins.count - abandons.total` => `wins.total - wins.count`
=> fix pie chart

react_main/src/components/Basic.jsx
fixes Secret Hitler Execution
but there's still 1 empty alert message in Secret Hitler; at least it won't crash everything now
=> fix: do not crash the app when Message content is undefined

Games/core/Meeting.js, Games/types/Mafia/Game.js
```
2023-08-06T20:25:23.384Z error: meeting is not defined 
ReferenceError: meeting is not defined
at MafiaGame.isMustAct (/home/ec2-user/um/Games/types/Mafia/Game.js:157:7)
at new Meeting (/home/ec2-user/um/Games/core/Meeting.js:32:25)
```
=> fix(mafia): mustact mustcondemn breaking games

Games/types/Mafia/roles/cards/ResetRolesOnDeath.js
Fixes #827 
happens on second butterfly death, because second butterfly has data.originalRoles deleted
=> fix(mafia): butterfly reset roles should preserve role data

Games/types/Mafia/roles/Cult/CatLady.js, Games/types/Mafia/roles/Cult/Diabolist.js, data/roles.js
based on conversations with other devs and the community
two roles are being realigned to cult due to theme/flavor reasons as well as mechanic reasons: cat lady and diabolist
cult lacked a voting role or a roleblocking/rolelearning role, so these two take those slots
future plans for a role that allows mafia and cult to joint is in the works based on these same conversations, but the code for winCheck is annoying so that's WIP
=> feat: catlady/diabolist are culties

Games/types/Mafia/roles/cards/WinWithMafia.js
```
2023-08-11T21:48:51.758Z error: Cannot read property 'length' of undefined 
TypeError: Cannot read property 'length' of undefined
at Hooker.check (/home/ec2-user/um/Games/types/Mafia/roles/cards/WinWithMafia.js:69:67)
at MafiaGame.checkWinConditions (/home/ec2-user/um/Games/types/Mafia/Game.js:280:27)
at MafiaGame.checkGameEnd (/home/ec2-user/um/Games/core/Game.js:1418:36)
```
=> fix: seer check get checking length on undefined

Games/types/Mafia/roles/Village/King.js, Games/types/Mafia/roles/Village/Loudmouth.js, Games/types/Mafia/roles/Village/Scapegoat.js, Games/types/Mafia/roles/Village/Sleepwalker.js, Games/types/Mafia/roles/Village/Trickster.js, data/roles.js
King, Scapegoat, Sleepwalker, and Trickster are now self-aware by default
Humble modifier can always be used for previous functionality
=> feat: most roles are not humble

routes/anonymousDeck.js
I think it counts the whole payload, rather than 1 image. Plus, it resizes the images anyways.
=> raise image size limit for decks

Games/types/Mafia/roles/cards/BanquetInvite.js
chef has always been mega OP because of its ability to invite itself to the banquet
this nerfs chef
=> fix: chef cannot self-invite

Games/types/Mafia/roles/cards/FrustratedCondemnation.js
Hotfix. Frustrated as a modifier should not be revealed to the person with it
=> fix: frustrated is hidden

Games/types/Mafia/Player.js, data/modifiers.js
All this does is change the "Graveyard participation is required. Please stay in the game." message so players will be able to tell at a glance that graveyard participation is required.
=> Update Graveyard Required death message

Games/core/Game.js, Games/types/Mafia/roles/Cult/Conjuror.js, Games/types/Mafia/roles/Village/Butler.js, Games/types/Mafia/roles/cards/Add2Banished.js, Games/types/Mafia/roles/cards/VoteWithMaster.js, data/modifiers.js, data/renamedRoles.js, data/roles.js, db/schemas.js, react_main/src/pages/Play/CreateSetup/CreateMafiaSetup.jsx, routes/setup.js
Banished roles won't spawn normally in closed setups. Banished roles can be added to the game by increasing a the Banished Count during setup creation.
Conjuror adds 2 Banished Roles regardless of the Banished Count to game in closed setups.  
Butler has a vote weight of 0. Each night chooses a player to have a vote weight of 2.
=> Conjuror and Butler roles (Baron and Butler from BOTC) + Banished modifer (Outsiders from BOTC)

Games/types/Mafia/roles/Village/Courtier.js, Games/types/Mafia/roles/Village/Debtor.js, Games/types/Mafia/roles/Village/Minstrel.js, Games/types/Mafia/roles/cards/Disloyal.js, Games/types/Mafia/roles/cards/GainGunIfMafiaAbstained.js, Games/types/Mafia/roles/cards/GuessRoleOrDie.js, Games/types/Mafia/roles/cards/LearnAndLifeLinkToPlayer.js, Games/types/Mafia/roles/cards/Loyal.js, Games/types/Mafia/roles/cards/MagusGame.js, Games/types/Mafia/roles/cards/MindRotEveryoneOnEvilCondemn.js, Games/types/Mafia/roles/cards/MindRotRoleFor3Nights.js, Games/types/Mafia/roles/cards/NightCaroler.js, data/modifiers.js, data/roles.js
Added Minstrel, If evil is condemned all players are inflicted with Mind rot.
added Courtier, Once per game can choose a role, If the Role is in play all players with are inflicted with mind rot for 3 nights.
added Grandmother as Married Modifier, On learns a player and their role, If that player is killed at night by another alignment, You also die.
added Gambler as Debtor, Each night must choose a player and a role from the setup. If the selected player isn't the selected role, the Debtor dies.
Buff: Caroler in False Mode no longer breaks the game if a town player vegs. (I think)
Better Magus Description.
Cannoneer now only gets a Gun Once.
=> More Clocktower Roles, Cannoneer Fix

Games/core/Player.js, Games/types/Mafia/Action.js, Games/types/Mafia/Game.js, Games/types/Mafia/effects/CannotRoleShare.js, Games/types/Mafia/effects/FalseMode.js, Games/types/Mafia/effects/MustRoleShare.js, Games/types/Mafia/events/CultureExchange.js, Games/types/Mafia/items/RoleShareAccept.js, Games/types/Mafia/items/RoleSharing.js, Games/types/Mafia/roles/Cult/Cthulhu.js, Games/types/Mafia/roles/Cult/Doomsayer.js, Games/types/Mafia/roles/Mafia/Blackmailer.js, Games/types/Mafia/roles/Mafia/Bully.js, Games/types/Mafia/roles/Mafia/Dealer.js, Games/types/Mafia/roles/Village/Apothecary.js, Games/types/Mafia/roles/Village/Brute.js, Games/types/Mafia/roles/Village/Recluse.js, Games/types/Mafia/roles/cards/CleanseOnRoleShare.js, Games/types/Mafia/roles/cards/CleanseVisitors.js, Games/types/Mafia/roles/cards/ConvertOnRoleShare.js, Games/types/Mafia/roles/cards/ForceSplitDecision.js, Games/types/Mafia/roles/cards/MakeInsaneOnRoleShare.js, Games/types/Mafia/roles/cards/MakeShyOnRoleShare.js, Games/types/Mafia/roles/cards/MakeSkittishOnRoleShare.js, Games/types/Mafia/roles/cards/ModifierLoud.js, Games/types/Mafia/roles/cards/Vain.js, Games/types/Mafia/roles/cards/Weak.js, data/roles.js
Assassin nerf- If an Assassin is created mid game they can no Longer spawn President as a Dead Player.
Filibuster and other roles lose their condemn/Kill immunities when changing roles.
New Role Brute (Town)/Bully (Mafia), Players who Role Share with you must accept all future role/alignment shares.
New Role Recluse (Town)/Blackmailer (Mafia), Players who Role Share with you cannot accept all future role/alignment shares. (They also can't send role/alignment shares.)
New* Role Dealer- Mafia version of Apothecary.
Apothecary Buff- Players who role share with an Apothecary are cleansed. (Also applies to Dealer).
Cthulhu Buff- applies Insanity to players who Role Share with them.
Doomsayer Buff- Converts players who Role Share
New Event- Culture Exchange, Enables Role Sharing for 2 players …
=> Role Sharing Roles and Bug Fixes

Games/types/Mafia/roles/cards/TurnIntoTraitorOnMafiaKill.js
As is, guiser voting yes to steal identity while targeting a turncoat with mafia meeting will convert them into a traitor then kill them.
Turncoat would listen to the emitted immune event when guiser steal identity action checks for immunity, causing the conversion to happen sooner in priority than maf kill. Adding temp immunity allows turncoat to keep its mafia immunity for the entire night that it gets converted.
=> Fixed turncoat guiser kill interaction

Games/core/Action.js, Games/core/Player.js, Games/types/Mafia/roles/cards/IdentityStealer.js, lib/sockets.js, test/Games/Mafia.test.js
For: https://github.com/UltiMafia/Ultimafia/issues/22
- Fixed guiser going thru armor immunity. It was the same bug in nature as the turncoat bug from https://github.com/UltiMafia/Ultimafia/pull/1782 so I tried a different approach to fixing it this time. The dominates check for identity stealer should no longer cause immune events.
- Fixed alerts being given to the wrong player when guising occurred; swapIdentity now additionally swaps the recipients of alerts that are presently queued.
- Added some guiser tests. The sockets.js change supports this because it's a necessary function for swapIdentity.
Tested the alerts issue locally by having the gunsmith give a gun to a cop then verifying that when they were guised, the dead player received the alert for the gun and not the guiser.
=> Fixes for guiser interaction with armor, alerts

Games/core/Game.js, Games/types/Mafia/roles/cards/IdentityStealer.js
This picture shows the bug where the cop got kicked for not voting but the guiser got vegged instead because they stole the identity of the cop:
The cop is dead even though the veg didn't target them because they got killed normally by mafia.
This happens because identity steal occurs before the queued veg action. When I tried to reproduce the bug after I made my changes, the expected behavior of only the cop vegging occurred.
I don't know if this is the best possible fix for this bug but it feels like a safe resolution to me.
=> Fixed bug where guiser vegged if target kill vegged

data/constants.js, db/schemas.js, react_main/src/components/Popover.jsx, react_main/src/css/game.css, react_main/src/css/user.css, react_main/src/pages/Game/Game.jsx, react_main/src/pages/User/PieChart.jsx, react_main/src/pages/User/Profile.jsx, react_main/src/pages/User/User.jsx, routes/auth.js, routes/mod.js, routes/user.js
Resolves #1517 and #1518
Miniprofile appears whenever you hover over the panel of a user inside a game. You can click on the user's panel to "lock" the miniprofile in place. Clicking on the user's name inside the miniprofile takes you the user's profile. Pronouns are conditionally displayed if set. Pie chart is displayed using the same mechanism from the profile page. The contents of the miniprofile are populated from a REST request that happens once per user in the game per refresh of your page.
Pronouns are set from your profile, they default to the empty string and your profile has a default message in place of your pronouns if they are still empty. You can edit them exactly like your bio - the limit is 15 characters (it can be increased but it'd need to be tweaked to play nice with …
=> Added user miniprofile and pronouns

Games/types/Mafia/information/RevealEvilPlayersInfo.js, Games/types/Mafia/information/RevealInfo.js, Games/types/Mafia/information/RevealPlayersWithRoleInfo.js, Games/types/Mafia/items/Retirement.js, Games/types/Mafia/roles/cards/BecomeAlignmentOfVisitors.js, Games/types/Mafia/roles/cards/CheckSuccessfulVisit.js, Games/types/Mafia/roles/cards/ConvertIfVisitsAllMafia.js, Games/types/Mafia/roles/cards/FalseModifier.js, Games/types/Mafia/roles/cards/FavorableModifier.js, Games/types/Mafia/roles/cards/MakeAllVillageInfoFalse.js, Games/types/Mafia/roles/cards/Omniscient.js, Games/types/Mafia/roles/cards/RevealEvilPlayersToSelf.js, Games/types/Mafia/roles/cards/TrueModifier.js, Games/types/Mafia/roles/cards/UnfavorableModifier.js, Games/types/Mafia/roles/cards/WinWithCurrentAlignment.js, data/modifiers.js, data/roles.js
(The Modifiers make the info do the thing) for all info excluding Statistician
Politician can now win when dead. 
Hitchhiker can win with Independent roles that visit it.
Removed the checking False Mode and the Picciotto False Mode.
Nyarlathotep can False Mode Seer and Retired roles now.
Notes: Rotten is the same as False for all info roles except Caroler, Comedian, Neighbor, and Santa.
=> Seer and Retired Info Files + False, True, Naive, Paranoid Modifiers + Hitchhiker and Politician buffs

Games/core/Meeting.js
It's a little hacky but it's a quick and easy solution for preventing people from just giving kudos to themselves
=> Added workaround for exclude self not working properly in group meetings

Games/core/Game.js, Games/types/Mafia/items/TreasureChest.js, Games/types/Mafia/roles/Village/Admiral.js, Games/types/Mafia/roles/cards/Puppeteering.js, data/roles.js
Example, If a setup is made with an Assassin but no President because Assassin creates a president it will still say the president-Assassin interaction.
=> /special now includes Roles added by Other Roles

react_main/src/components/Form.jsx, react_main/src/css/settings.css, routes/user.js
- Fixed the issue where custom emotes couldn't be animated
- Increased upload size of emotes to 30x30. In most contexts they will be resized to 20x20, but the quality is still better than if they were uploaded at 20x20
- Touched up displays of emotes on settings page to match the way that they're rendered in game
HOWEVER:
- animation is disabled if the uploaded file is greater than 30 height or width px, this is because the sharp library's resize image operation disables animation. Users will want to resize their animated files to 30x30 themselves. I see no workaround for this.
- animated GIFs with transparency don't seem to play nice with this library, e.g. ditto.gif. Users will want to find their own means of converting their GIF to webp with the correct transparency themselves. I …
=> Added support for animated custom emtoes

react_main/src/pages/Play/Host/HostAcrotopia.jsx, react_main/src/pages/Play/Host/HostDefaults.js, react_main/src/pages/Play/Host/HostGhost.jsx, react_main/src/pages/Play/Host/HostJotto.jsx, react_main/src/pages/Play/Host/HostLiarsDice.jsx, react_main/src/pages/Play/Host/HostMafia.jsx, react_main/src/pages/Play/Host/HostResistance.jsx, react_main/src/pages/Play/Host/HostSecretDictator.jsx, react_main/src/pages/Play/Host/HostWackyWords.jsx, react_main/src/pages/Play/LobbyBrowser/RecentlyPlayedSetups.jsx
I had to refactor the default options quite a bit since the most played setups component has no context for what options it should use for hosted setups, unlike the existing game browser rehost button which can just pull them from the finished game.
The defaults will be used when rehosting via popular setups. This might not be ideal for certain modes such as liar's dice - you can't use that rehost button to start a lobby with spot on turned on for example.
I tested the hosting of each minigame to make sure things didn't break.
=> Added rehost button to most popular setups, refactored default options

Games/types/Mafia/roles/cards/CauseBanishedEventsOnDeath.js, Games/types/Mafia/roles/cards/ChoosePlayerOnDeath.js, Games/types/Mafia/roles/cards/ConvertTownBlueOnDeath.js, Games/types/Mafia/roles/cards/DisableVotingIfDeadAtNight.js, Games/types/Mafia/roles/cards/EclipseOnDeath.js, Games/types/Mafia/roles/cards/GiveShavingCreamOnDeath.js, Games/types/Mafia/roles/cards/IfVotedForceCondemn.js, Games/types/Mafia/roles/cards/KillVillagePlayerOnDeath.js, Games/types/Mafia/roles/cards/ResetRolesOnDeath.js, Games/types/Mafia/roles/cards/RevealTargetOnDeath.js, Games/types/Mafia/roles/cards/SacrificeSameRole.js, Games/types/Mafia/roles/cards/VotesAnonymousOnDeath.js
Delirum now disable the abilites of Typist, Lightkeeper, Schoolmarm, Secretary, Sheep, Gatekeeper, Butterfly, Barber, Mooncalf, Benandante, and Princess. 
Oracle- Can now be blocked properly if not resolute. (Before it would use target from previous day)
=> More Delirum Changes + Oracle Fix

Games/types/Resistance/items/Leader.js
bug: 
currently in 5p resistance setup with 3 town and 2 mafias, the leader isn't participating in the team approval meeting.
This leads to forced nl situation where both mafias simply vote 'no' forever.
solution:
let leader vote too
I haven't tested this change, just did a ctr+f and comment out, so need a review
=> Resistance: all should approve team to avoid force nl

react_main/src/pages/Play/Host/HostAcrotopia.jsx, react_main/src/pages/Play/Host/HostCardGames.jsx, react_main/src/pages/Play/Host/HostDefaults.js, react_main/src/pages/Play/Host/HostGhost.jsx, react_main/src/pages/Play/Host/HostJotto.jsx, react_main/src/pages/Play/Host/HostLiarsDice.jsx, react_main/src/pages/Play/Host/HostMafia.jsx, react_main/src/pages/Play/Host/HostResistance.jsx, react_main/src/pages/Play/Host/HostSecretDictator.jsx, react_main/src/pages/Play/Host/HostWackyWords.jsx, react_main/src/pages/Play/LobbyBrowser/RecentlyPlayedSetups.jsx
I was originally going to just enable spectating by default but then I found that that doesn't actually work. I ended up refactoring a bunch of stuff:
- enabled spectating by default
- added configureDuration to the common options
- removed scheduled from the common options
- fixed a bug in resistance where it was always scheduling the game if spectating was on
- tracked the persisted options of each game type separately
- added a gimmick that will let us force reset user's persisted options by gametype
All users will have their saved options reset after this change because I restructured the way that they're stored. I was going to do that no matter what because I wanted the default spectating enabled to take effect.
I tested each game type to verify that my options were being saved.
=> Fixed defaults not persisting, spectating default enabled, refactored

Games/types/Mafia/Player.js, Games/types/Mafia/Winners.js, Games/types/Mafia/const/ImportantMeetings.js, Games/types/Mafia/effects/BecomeRoleOnDeath.js, Games/types/Mafia/effects/Delirious.js, Games/types/Mafia/effects/StylePoints.js, Games/types/Mafia/roles/Cult/DreamEater.js, Games/types/Mafia/roles/Cult/Facehugger.js, Games/types/Mafia/roles/Mafia/Stylist.js, Games/types/Mafia/roles/cards/AppearAsVanillaEvil.js, Games/types/Mafia/roles/cards/ConvertToChosenRoleOnDeath.js, Games/types/Mafia/roles/cards/HauntDreams.js, Games/types/Mafia/roles/cards/Holy.js, Games/types/Mafia/roles/cards/StyleContest.js, Games/types/Mafia/roles/cards/Unholy.js, data/modifiers.js, data/roles.js, package-lock.json, react_main/src/css/gameCardGames.css, react_main/src/css/roles.css
10 of spades no longer uses 10 of clubs sprite
Facehugger from discord message Golbolco sent me.
BOTC leech as Dream Eater, Each night can kill a player. On night 1 chooses a player as Vessel, The vessel is delirious. The dream eater can only be killed by killing the vessel.
Holy- Can only target non-demonic players
Unholy- Can only target demonic players.
I also gave into my intrusive thoughts and added the Stylist role. It lets the mafia member who says their role in chat the most win even if mafia loses.
=> 10 of Spades fix + Facehugger Role + Botc Leech + Holy and Unholy Modifers

Games/types/Mafia/items/Gun.js, Games/types/Mafia/roles/cards/GiveTommyGun.js, Games/types/Mafia/roles/cards/TailorSuit.js, data/roles.js
Tailor does not tell players about suits
Old tailor can be made with Clumsy
Gunrunner guns now can only kill players of the same alignment as the shooter. (Village can only kill Village, Mafia can only kill mafia, etc)
Gunrunner can now gun mafia and themselves.
Old Gunrunner can be made with disloyal.
Zealot description improvement (I think)
=> tailor and Gunrunner changes

react_main/src/components/EmotePicker.jsx
guests are getting critical error and staring at a blank screen
0.chunk.js:217627 Uncaught TypeError: Cannot read properties of undefined (reading 'customEmotes')
at EmotePicker (1.chunk.js:1800:42)
at renderWithHooks (0.chunk.js:183740:22)
at mountIndeterminateComponent (0.chunk.js:186069:17)
at beginWork (0.chunk.js:187006:20)
at HTMLUnknownElement.callCallback (0.chunk.js:171043:18)
at Object.invokeGuardedCallbackDev (0.chunk.js:171087:20)
at invokeGuardedCallback (0.chunk.js:171135:35)
at beginWork$1 (0.chunk.js:190906:11)
at performUnitOfWork (0.chunk.js:190030:16)
at workLoopSync (0.chunk.js:190006:26)
at performSyncWorkOnRoot (0.chunk.js:189676:13)
at 0.chunk.js:180652:28
at unstable_runWithPriority (0.chunk.js:218042:16)
at runWithPriority$1 (0.chunk.js:180607:14)
at …
=> fix(emotes): null check

react_main/src/Main.jsx, react_main/src/components/Setup.jsx, react_main/src/css/game.css, react_main/src/css/host.css, react_main/src/css/play.css, react_main/src/css/setup.css, react_main/src/css/user.css, react_main/src/pages/Game/Game.jsx, react_main/src/pages/Play/Host/HostBrowser.jsx, react_main/src/pages/Play/LobbyBrowser/GameRow.jsx, react_main/src/pages/Play/LobbyBrowser/LobbyBrowser.jsx, react_main/src/pages/Play/LobbyBrowser/RecentlyPlayedSetups.jsx, react_main/src/pages/User/Profile.jsx, react_main/src/pages/User/User.jsx
Note: The "lobby name goes here" thing is not included in this pull request I was just using that to test how well it fit into the space. At some point I would add lobby names that default to "nearbear's lobby" and such. At some point I would like to add color coded rows but for the moment I'm quite exhausted on front end stuff.
Summary of changes:
- Made the Setup component fixed width based on the maxRolesCount that you give it
- Combined the game type button, setup name, and roles list all into one
- Tweaked recently played games widget
- Fixed the in-love text overflowing the profile
- Fixed alternating colors in recent games section of profile
- Compacted profile greatly for mobile - lots of excess padding
- Compacted GameRow greatly for mobile - now things will stack vertically to …
=> Reworked Setup component

react_main/src/pages/User/Settings.jsx
since there's no thing as multiple accounts with the same login, i thought 'Account' would make more sense
=> style: fix the spelling of Account section

Games/core/Game.js, Games/types/Mafia/Information.js, Games/types/Mafia/information/TwoNotRolesInfo.js, Games/types/Mafia/items/ReturnToRole.js, Games/types/Mafia/roles/Cult/Sidhe.js, Games/types/Mafia/roles/Mafia/Consigliere.js, Games/types/Mafia/roles/Village/Clairvoyant.js, Games/types/Mafia/roles/Village/Jack, Games/types/Mafia/roles/cards/BecomeBanishedRoleFor1Phase.js, Games/types/Mafia/roles/cards/BecomeUndercoverEvil.js, Games/types/Mafia/roles/cards/Learn2NotRoles.js, data/modifiers.js, data/roles.js, routes/setup.js
Banished roles no longer spawn in non-closed setups.
Clairvoyant, "Each night choose a player, learn 2 roles that aren't that player's role."
Jack, "At night choose a banished role from your alignment, gains it's abilities until the next night. Cannot choose a role they already used"
Consigliere, Jack but mafia
Sidhe, Jack but cult.
=>  Banished change+ Jack/Consigliere/Sidhe and Clairvoyant roles

react_main/src/pages/Game/Game.jsx, react_main/src/pages/Play/LobbyBrowser/GameRow.jsx, routes/game.js
Probably there is a better solution with either different routes for spectating/joining, a Custom Hook for different game modes etc. Open to ideas, but this is a quick fix and works
=> fix: allow spectating ranked games without red heart requirement

react_main/src/css/user.css, react_main/src/pages/Game/Game.jsx
- fixed large nameplates not appearing grayscale when dead
- fixed indent being off when dead
- fixed bug where minigames prevented messages from a previous state from being quoted properly
- attempting to quote from a previous state resulted in an empty message which made nameplate not appear in default styles
- fixed /me not applying italics (im not actually sure how this broke, i didn't change it?)
=> fixed various ui bugs

Games/types/Mafia/roles/cards/ModifierConfused.js, Games/types/Mafia/roles/cards/PublicReveal.js, data/modifiers.js, react_main/src/components/Roles.jsx
Modifiers have 4 categories to choose from so they are not visible by default. "Items", "Visits", "Appearance", "Other"
Some modifiers that do similar things are now next to each other in the list. Disloyal+Loyal, Holy+Unholy, etc.
Exposed no longer reveals players to self so it can be used with humble for Meme setups.
Confused no longer does delirium.
=> Modifier categories and resort

Games/types/ConnectFour/Game.js, Games/types/Mafia/Player.js, Games/types/Mafia/information/RevealInfo.js, Games/types/Mafia/items/RoleShareAccept.js, Games/types/Mafia/roles/Village/Soprano.js, Games/types/Mafia/roles/cards/AppearAsVanillaEvil.js, Games/types/Mafia/roles/cards/BecomeRoleForNight.js, Games/types/Mafia/roles/cards/IfVotedForceCondemn.js, Games/types/Mafia/roles/cards/NightSaveAndLifeLink.js, Games/types/Mafia/roles/cards/Pranked.js, data/roles.js
Princess, Prankster, Monkey, Ape can now use Disloyal, Loyal, etc.
Princess- Will now condemn the first to vote them regardless of alignment.
For Old Princess use Princess (Loyal)
For BOTC Virgin use Princess (Loyal/Refined)
Soprano role from shego's suggestion in the discord
You can now win in connect four if your chip is placed in the middle of a chain of 4.
Role Sharing now works properly with Appearance changing roles
=> Princess changes + Soprano role + Connect 4 Fixes + Modifiers for Prankster, Princess, Monkey, Ape

Games/core/Meeting.js, Games/types/Mafia/Player.js, Games/types/Mafia/const/ImportantMeetings.js, Games/types/Mafia/effects/CursedVote.js, Games/types/Mafia/effects/DayTask.js, Games/types/Mafia/effects/Wrangled.js, Games/types/Mafia/items/Room.js, Games/types/Mafia/roles/cards/BookieWager.js, Games/types/Mafia/roles/cards/DeliriateEveryoneOnEvilCondemn.js, Games/types/Mafia/roles/cards/ForceSplitDecision.js, Games/types/Mafia/roles/cards/IfVotedForceCondemn.js, Games/types/Mafia/roles/cards/WinByCondemning.js, Games/types/Mafia/roles/cards/WinIfCondemned.js, Games/types/Mafia/roles/cards/WinIfTargetDead.js, data/modifiers.js, data/roles.js, react_main/src/components/Setup.jsx
Role Sharing can now only be done within a room.
Talking and Voting Dead work in rooms.
Various roles now work in Assassin roles.
Added Mastermind from 2 Rooms and a Boom as a Special Interaction for Fool, If an Assassin is present, a Fool will win at the end of the game if they were elected Leader of 2 different Rooms during the game.
Added Minion from 2 Rooms and a Boom as Special Interaction for Executioner, If an Assassin is present, an Executioner will win at the end of the game if they are never in a room when the room leader changes.
Added Bomb-Bot from 2 Rooms and a Boom as Special Interaction for Vengeful Spirit, If an Assassin is present, a Vengeful Spirit will win if the Assassin kills them and the Assassin does not kill any Presidents, Senators, or Vital Village roles.
Made …
=> More Assassin Updates (everyone loves Assassin Updates) + Jazzman Updates (No one loves Jazzman)

Games/core/Game.js, Games/types/Mafia/Game.js, db/schemas.js, react_main/src/components/Popover.jsx, react_main/src/components/Roles.jsx, react_main/src/css/roles.css, react_main/src/pages/Game/Game.jsx, react_main/src/pages/Game/MafiaGame.jsx, react_main/src/pages/Play/CreateSetup/CreateBrowser.jsx, routes/setup.js, scripts/mongo/migrate-setup-game-settings.js
- Converted gameSettings DB representation to object of key value pairs where the value is either a boolean or a number
- Added migration script, the script is safe to run multiple times and can be done in advance of upgrading (run using mongosh, instructions below
- Added game settings icons to setup popover, kudos to SawJester for adding the game settings icon component
- Fixed rendering of digits for all sizes of icons (previously they were misaligned for closed setups)
Migration instructions (syntax is probably a bit off, I wrote this from memory):
```
docker exec -it mongodb mongosh
use admin
db.auth('admin', <password>)
use beyondmafia
load('/scripts/migrate-setup-game-settings.js')
```
=> Added migration script, added game setting icons to popver
